// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: DCO_v4_ILI9488

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Main
void ui_Main_screen_init(void);
lv_obj_t * ui_Main;
lv_obj_t * ui_PresetNumberContainer;
lv_obj_t * ui_PresetNShadow;
lv_obj_t * ui_PresetN;
lv_obj_t * ui_TopBarPanel;
lv_obj_t * ui_OSC1Level;
lv_obj_t * ui_OSC2Level;
lv_obj_t * ui_SUBLevel;
lv_obj_t * ui_ADSRContainer;
lv_obj_t * ui_ADSR1AttackBar;
lv_obj_t * ui_ADSR1DecayBar;
lv_obj_t * ui_ADSR1SustainBar;
lv_obj_t * ui_ADSR1ReleaseBar;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Label10;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Label12;
lv_obj_t * ui_ADSRContainer1;
lv_obj_t * ui_ADSR2AttackBar;
lv_obj_t * ui_ADSR2DecayBar;
lv_obj_t * ui_ADSR2SustainBar;
lv_obj_t * ui_ADSR2ReleaseBar;
lv_obj_t * ui_Label13;
lv_obj_t * ui_Label14;
lv_obj_t * ui_Label15;
lv_obj_t * ui_Label16;
lv_obj_t * ui_PresetNamePanel;
lv_obj_t * ui_BottomContainer;
lv_obj_t * ui_PresetNameShadow;
lv_obj_t * ui_PresetName;
lv_obj_t * ui_BottomMessagePanel;
lv_obj_t * ui_CommandMessageShadow;
lv_obj_t * ui_CommandMessage;
lv_obj_t * ui_CommandValueShadow;
lv_obj_t * ui_CommandValue;
lv_obj_t * ui_PresetSavePanel;
lv_obj_t * ui_PresetSaveFromTitleShadow;
lv_obj_t * ui_PresetSaveFromTitle;
lv_obj_t * ui_PresetNOLDShadow;
lv_obj_t * ui_PresetNOLD;
lv_obj_t * ui_PresetNameOLDShadow;
lv_obj_t * ui_PresetNameOLD;
lv_obj_t * ui_PresetSaveToShadow;
lv_obj_t * ui_PresetSaveTo;
lv_obj_t * ui_PresetNNewShadow;
lv_obj_t * ui_PresetNNew;
lv_obj_t * ui_PresetNameNew;
lv_obj_t * ui_PresetNameNewShadow;
lv_obj_t * ui_PresetNewName;
lv_obj_t * ui_PresetSavedMesage;


// SCREEN: ui_Main1
void ui_Main1_screen_init(void);
lv_obj_t * ui_Main1;
lv_obj_t * ui_PresetNamePanel1;
lv_obj_t * ui_PresetSavePanel1;
lv_obj_t * ui_PresetSaveFromTitleShadow1;
lv_obj_t * ui_PresetSaveFromTitle1;
lv_obj_t * ui_PresetNOLDShadow1;
lv_obj_t * ui_PresetNOLD1;
lv_obj_t * ui_PresetNameOLDShadow1;
lv_obj_t * ui_PresetNameOLD1;
lv_obj_t * ui_PresetSaveToShadow1;
lv_obj_t * ui_PresetSaveTo1;
lv_obj_t * ui_PresetNNewShadow1;
lv_obj_t * ui_PresetNNew1;
lv_obj_t * ui_PresetNameNew1;
lv_obj_t * ui_PresetNameNewShadow1;
lv_obj_t * ui_PresetNewName1;
lv_obj_t * ui_PresetSavedMesage1;
lv_obj_t * ui_TabView1;
lv_obj_t * ui_DCOTab;
lv_obj_t * ui_TopBarPanel1;
lv_obj_t * ui_OSC1Level1;
lv_obj_t * ui_OSC2Level1;
lv_obj_t * ui_SUBLevel1;
lv_obj_t * ui_ENVTab;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Switch2;
lv_obj_t * ui_Switch3;
lv_obj_t * ui_Switch4;
lv_obj_t * ui_Switch5;
lv_obj_t * ui_Switch6;
lv_obj_t * ui_VCFTab;
lv_obj_t * ui_ChartVCFAttack;
lv_obj_t * ui_ChartVCFAttack_Xaxis;
lv_obj_t * ui_ChartVCFAttack_Yaxis1;
lv_obj_t * ui_ChartVCFAttack_Yaxis2;
lv_obj_t * ui_ChartVCFDecay;
lv_obj_t * ui_ChartVCFDecay_Xaxis;
lv_obj_t * ui_ChartVCFDecay_Yaxis1;
lv_obj_t * ui_ChartVCFDecay_Yaxis2;
lv_obj_t * ui_Switch1;
lv_obj_t * ui_VCATab;
lv_obj_t * ui_SettingsTab;
lv_obj_t * ui_ENVTab1;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Label8;


// SCREEN: ui_MANUALCALIBRATION
void ui_MANUALCALIBRATION_screen_init(void);
lv_obj_t * ui_MANUALCALIBRATION;
lv_obj_t * ui_calibrationTabs;
lv_obj_t * ui_autoCalibrationPage;
lv_obj_t * ui_PWCalibrationPage;
lv_obj_t * ui_fullCalibrationPage;
lv_obj_t * ui_manualCalibrationPage;
lv_obj_t * ui_manualCalibrationPanel;
lv_obj_t * ui_DCONTITLE;
lv_obj_t * ui_oscillatorNTitleShadow;
lv_obj_t * ui_oscillatorNTitle;
lv_obj_t * ui_DCON;
lv_obj_t * ui_oscillatorNShadow;
lv_obj_t * ui_oscillatorN;
lv_obj_t * ui_OFFSETTITLE;
lv_obj_t * ui_offsetTitleShadow;
lv_obj_t * ui_offsetTitle;
lv_obj_t * ui_OFFSET;
lv_obj_t * ui_calibrationOffsetShadow;
lv_obj_t * ui_calibrationOffset;
lv_obj_t * ui_GAPTITLE;
lv_obj_t * ui_gapTitleShadow;
lv_obj_t * ui_gapTitle;
lv_obj_t * ui_GAP;
lv_obj_t * ui_calibrationGapShadow;
lv_obj_t * ui_calibrationGap;
lv_obj_t * ui_WAVEFORMTITLE;
lv_obj_t * ui_waveformTitleShadow;
lv_obj_t * ui_waveformTitle;
lv_obj_t * ui_WAVEFORM;
lv_obj_t * ui_waveformShadow;
lv_obj_t * ui_waveform;
lv_obj_t * ui_calibrationCompleteMessage;
lv_obj_t * ui____initial_actions0;
const lv_image_dsc_t * ui_imgset_techno_background_with_connecting_grid_[1] = {&ui_img_techno_background_with_connecting_grid_2201_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Main_screen_init();
    ui_Main1_screen_init();
    ui_MANUALCALIBRATION_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Main);
}
