// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: DCO_v4_ILI9488

#ifndef _DCO_V4_ILI9488_UI_H
#define _DCO_V4_ILI9488_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

// SCREEN: ui_Main
void ui_Main_screen_init(void);
extern lv_obj_t * ui_Main;
extern lv_obj_t * ui_PresetNumberContainer;
extern lv_obj_t * ui_PresetNShadow;
extern lv_obj_t * ui_PresetN;
extern lv_obj_t * ui_TopBarPanel;
extern lv_obj_t * ui_OSC1Level;
extern lv_obj_t * ui_OSC2Level;
extern lv_obj_t * ui_SUBLevel;
extern lv_obj_t * ui_ADSRContainer;
extern lv_obj_t * ui_ADSR1AttackBar;
extern lv_obj_t * ui_ADSR1DecayBar;
extern lv_obj_t * ui_ADSR1SustainBar;
extern lv_obj_t * ui_ADSR1ReleaseBar;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_ADSRContainer1;
extern lv_obj_t * ui_ADSR2AttackBar;
extern lv_obj_t * ui_ADSR2DecayBar;
extern lv_obj_t * ui_ADSR2SustainBar;
extern lv_obj_t * ui_ADSR2ReleaseBar;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_PresetNamePanel;
extern lv_obj_t * ui_BottomContainer;
extern lv_obj_t * ui_PresetNameShadow;
extern lv_obj_t * ui_PresetName;
extern lv_obj_t * ui_BottomMessagePanel;
extern lv_obj_t * ui_CommandMessageShadow;
extern lv_obj_t * ui_CommandMessage;
extern lv_obj_t * ui_CommandValueShadow;
extern lv_obj_t * ui_CommandValue;
extern lv_obj_t * ui_PresetSavePanel;
extern lv_obj_t * ui_PresetSaveFromTitleShadow;
extern lv_obj_t * ui_PresetSaveFromTitle;
extern lv_obj_t * ui_PresetNOLDShadow;
extern lv_obj_t * ui_PresetNOLD;
extern lv_obj_t * ui_PresetNameOLDShadow;
extern lv_obj_t * ui_PresetNameOLD;
extern lv_obj_t * ui_PresetSaveToShadow;
extern lv_obj_t * ui_PresetSaveTo;
extern lv_obj_t * ui_PresetNNewShadow;
extern lv_obj_t * ui_PresetNNew;
extern lv_obj_t * ui_PresetNameNew;
extern lv_obj_t * ui_PresetNameNewShadow;
extern lv_obj_t * ui_PresetNewName;
extern lv_obj_t * ui_PresetSavedMesage;
// SCREEN: ui_Main1
void ui_Main1_screen_init(void);
extern lv_obj_t * ui_Main1;
extern lv_obj_t * ui_PresetNamePanel1;
extern lv_obj_t * ui_PresetSavePanel1;
extern lv_obj_t * ui_PresetSaveFromTitleShadow1;
extern lv_obj_t * ui_PresetSaveFromTitle1;
extern lv_obj_t * ui_PresetNOLDShadow1;
extern lv_obj_t * ui_PresetNOLD1;
extern lv_obj_t * ui_PresetNameOLDShadow1;
extern lv_obj_t * ui_PresetNameOLD1;
extern lv_obj_t * ui_PresetSaveToShadow1;
extern lv_obj_t * ui_PresetSaveTo1;
extern lv_obj_t * ui_PresetNNewShadow1;
extern lv_obj_t * ui_PresetNNew1;
extern lv_obj_t * ui_PresetNameNew1;
extern lv_obj_t * ui_PresetNameNewShadow1;
extern lv_obj_t * ui_PresetNewName1;
extern lv_obj_t * ui_PresetSavedMesage1;
extern lv_obj_t * ui_TabView1;
extern lv_obj_t * ui_DCOTab;
extern lv_obj_t * ui_TopBarPanel1;
extern lv_obj_t * ui_OSC1Level1;
extern lv_obj_t * ui_OSC2Level1;
extern lv_obj_t * ui_SUBLevel1;
extern lv_obj_t * ui_ENVTab;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Switch2;
extern lv_obj_t * ui_Switch3;
extern lv_obj_t * ui_Switch4;
extern lv_obj_t * ui_Switch5;
extern lv_obj_t * ui_Switch6;
extern lv_obj_t * ui_VCFTab;
extern lv_obj_t * ui_ChartVCFAttack;
extern lv_obj_t * ui_ChartVCFAttack_Xaxis;
extern lv_obj_t * ui_ChartVCFAttack_Yaxis1;
extern lv_obj_t * ui_ChartVCFAttack_Yaxis2;
extern lv_obj_t * ui_ChartVCFDecay;
extern lv_obj_t * ui_ChartVCFDecay_Xaxis;
extern lv_obj_t * ui_ChartVCFDecay_Yaxis1;
extern lv_obj_t * ui_ChartVCFDecay_Yaxis2;
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_VCATab;
extern lv_obj_t * ui_SettingsTab;
extern lv_obj_t * ui_ENVTab1;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
// SCREEN: ui_MANUALCALIBRATION
void ui_MANUALCALIBRATION_screen_init(void);
extern lv_obj_t * ui_MANUALCALIBRATION;
extern lv_obj_t * ui_calibrationTabs;
extern lv_obj_t * ui_autoCalibrationPage;
extern lv_obj_t * ui_PWCalibrationPage;
extern lv_obj_t * ui_fullCalibrationPage;
extern lv_obj_t * ui_manualCalibrationPage;
extern lv_obj_t * ui_manualCalibrationPanel;
extern lv_obj_t * ui_DCONTITLE;
extern lv_obj_t * ui_oscillatorNTitleShadow;
extern lv_obj_t * ui_oscillatorNTitle;
extern lv_obj_t * ui_DCON;
extern lv_obj_t * ui_oscillatorNShadow;
extern lv_obj_t * ui_oscillatorN;
extern lv_obj_t * ui_OFFSETTITLE;
extern lv_obj_t * ui_offsetTitleShadow;
extern lv_obj_t * ui_offsetTitle;
extern lv_obj_t * ui_OFFSET;
extern lv_obj_t * ui_calibrationOffsetShadow;
extern lv_obj_t * ui_calibrationOffset;
extern lv_obj_t * ui_GAPTITLE;
extern lv_obj_t * ui_gapTitleShadow;
extern lv_obj_t * ui_gapTitle;
extern lv_obj_t * ui_GAP;
extern lv_obj_t * ui_calibrationGapShadow;
extern lv_obj_t * ui_calibrationGap;
extern lv_obj_t * ui_WAVEFORMTITLE;
extern lv_obj_t * ui_waveformTitleShadow;
extern lv_obj_t * ui_waveformTitle;
extern lv_obj_t * ui_WAVEFORM;
extern lv_obj_t * ui_waveformShadow;
extern lv_obj_t * ui_waveform;
extern lv_obj_t * ui_calibrationCompleteMessage;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(
    ui_img_techno_background_with_connecting_grid_2201_png);    // assets/techno_background_with_connecting_grid_2201.png


LV_FONT_DECLARE(ui_font_Square140);
LV_FONT_DECLARE(ui_font_Square22);
LV_FONT_DECLARE(ui_font_radj148Semi);
LV_FONT_DECLARE(ui_font_radj22SEMI);
LV_FONT_DECLARE(ui_font_radj26Medium);
LV_FONT_DECLARE(ui_font_radjLight140);
LV_FONT_DECLARE(ui_font_radjMed32);
LV_FONT_DECLARE(ui_font_radjMed38);
LV_FONT_DECLARE(ui_font_radjSemi160);
LV_FONT_DECLARE(ui_font_radjSemi180);
LV_FONT_DECLARE(ui_font_square32);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
