// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: DCO_v4

#include "ui.h"


// COMPONENT BarCyberOrange

lv_obj_t * ui_BarCyberOrange_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_BarCyberOrange;
    cui_BarCyberOrange = lv_bar_create(comp_parent);
    lv_bar_set_range(cui_BarCyberOrange, 0, 127);
    lv_bar_set_value(cui_BarCyberOrange, 99, LV_ANIM_OFF);
    lv_bar_set_start_value(cui_BarCyberOrange, 0, LV_ANIM_OFF);
    lv_obj_set_width(cui_BarCyberOrange, 100);
    lv_obj_set_height(cui_BarCyberOrange, 10);
    lv_obj_set_x(cui_BarCyberOrange, 0);
    lv_obj_set_y(cui_BarCyberOrange, -15);
    lv_obj_set_align(cui_BarCyberOrange, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_BarCyberOrange,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_radius(cui_BarCyberOrange, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_BarCyberOrange, lv_color_hex(0xE1913B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_BarCyberOrange, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(cui_BarCyberOrange, lv_color_hex(0xFB6E32), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(cui_BarCyberOrange, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(cui_BarCyberOrange, 500, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(cui_BarCyberOrange, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_BarCyberOrange, lv_color_hex(0xA77F27), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_BarCyberOrange, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_BarCyberOrange, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(cui_BarCyberOrange, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(cui_BarCyberOrange, lv_color_hex(0xEBBB4F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(cui_BarCyberOrange, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(cui_BarCyberOrange, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(cui_BarCyberOrange, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(cui_BarCyberOrange, lv_color_hex(0xBD8929), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(cui_BarCyberOrange, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(cui_BarCyberOrange, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(cui_BarCyberOrange, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(cui_BarCyberOrange, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(cui_BarCyberOrange, 1200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_BarCyberOrange, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_BarCyberOrange, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_BarCyberOrange, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_BarCyberOrange, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(cui_BarCyberOrange, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_BarCyberOrange, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(cui_BarCyberOrange, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_BarCyberOrange, lv_color_hex(0xE1913B), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_BarCyberOrange, 220, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(cui_BarCyberOrange, lv_color_hex(0xF97F30), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(cui_BarCyberOrange, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(cui_BarCyberOrange, 500, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(cui_BarCyberOrange, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(cui_BarCyberOrange, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_BarCyberOrange, lv_color_hex(0xEFB95A), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_BarCyberOrange, 150, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_BarCyberOrange, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(cui_BarCyberOrange, LV_BORDER_SIDE_FULL, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(cui_BarCyberOrange, LV_BLEND_MODE_ADDITIVE, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(cui_BarCyberOrange, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(cui_BarCyberOrange, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(cui_BarCyberOrange,
                                                                                                      lv_obj_get_style_pad_right(cui_BarCyberOrange, LV_PART_MAIN) + 1, LV_PART_MAIN);
    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_BARCYBERORANGE_NUM);
    children[UI_COMP_BARCYBERORANGE_BARCYBERORANGE] = cui_BarCyberOrange;
    lv_obj_add_event_cb(cui_BarCyberOrange, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_BarCyberOrange, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_BarCyberOrange_create_hook(cui_BarCyberOrange);
    return cui_BarCyberOrange;
}

