// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: DCO_v4_ILI9488

#include "ui.h"


// COMPONENT BARADSR

lv_obj_t * ui_BARADSR_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_BARADSR;
    cui_BARADSR = lv_bar_create(comp_parent);
    lv_bar_set_range(cui_BARADSR, 0, 127);
    lv_bar_set_value(cui_BARADSR, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(cui_BARADSR, 0, LV_ANIM_OFF);
    lv_obj_set_width(cui_BARADSR, 163);
    lv_obj_set_height(cui_BARADSR, 10);
    lv_obj_set_x(cui_BARADSR, -1);
    lv_obj_set_y(cui_BARADSR, -30);
    lv_obj_set_align(cui_BARADSR, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(cui_BARADSR, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(cui_BARADSR,
                                                                                               lv_obj_get_style_pad_right(cui_BARADSR, LV_PART_MAIN) + 1, LV_PART_MAIN);
    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_BARADSR_NUM);
    children[UI_COMP_BARADSR_BARADSR] = cui_BARADSR;
    lv_obj_add_event_cb(cui_BARADSR, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_BARADSR, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_BARADSR_create_hook(cui_BARADSR);
    return cui_BARADSR;
}

