// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: DCO_v4_ILI9488

#ifndef _UI_COMP_BARADSR_H
#define _UI_COMP_BARADSR_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT BARADSR
#define UI_COMP_BARADSR_BARADSR 0
#define _UI_COMP_BARADSR_NUM 1
lv_obj_t * ui_BARADSR_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
