// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: DCO_v4

#ifndef _DCO_V4_UI_COMP_HOOK_H
#define _DCO_V4_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_BAR2_create_hook(lv_obj_t * comp);
void ui_comp_BarCyberOrange_create_hook(lv_obj_t * comp);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
