// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: DCO_v4_ILI9488

#include "ui.h"

void ui_Main_screen_init(void)
{
    ui_Main = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Main, lv_color_hex(0x1A0C06), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Main, lv_color_hex(0xE1913B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Main, 240, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Main, &ui_font_radj22SEMI, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetNumberContainer = lv_obj_create(ui_Main);
    lv_obj_remove_style_all(ui_PresetNumberContainer);
    lv_obj_set_width(ui_PresetNumberContainer, 308);
    lv_obj_set_height(ui_PresetNumberContainer, 173);
    lv_obj_set_x(ui_PresetNumberContainer, 0);
    lv_obj_set_y(ui_PresetNumberContainer, 30);
    lv_obj_set_align(ui_PresetNumberContainer, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_PresetNumberContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_PresetNumberContainer, lv_color_hex(0xBD814A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PresetNumberContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PresetNumberContainer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetNShadow = lv_label_create(ui_PresetNumberContainer);
    lv_obj_set_width(ui_PresetNShadow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PresetNShadow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PresetNShadow, 2);
    lv_obj_set_y(ui_PresetNShadow, -5);
    lv_obj_set_align(ui_PresetNShadow, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PresetNShadow, "208");
    lv_obj_set_style_text_color(ui_PresetNShadow, lv_color_hex(0xFF3B18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetNShadow, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_PresetNShadow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_PresetNShadow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PresetNShadow, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetNShadow, &ui_font_radjSemi180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PresetNShadow, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetN = lv_label_create(ui_PresetNumberContainer);
    lv_obj_set_width(ui_PresetN, 300);
    lv_obj_set_height(ui_PresetN, 150);
    lv_obj_set_x(ui_PresetN, -3);
    lv_obj_set_y(ui_PresetN, -1);
    lv_obj_set_align(ui_PresetN, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PresetN, "208");
    lv_obj_set_style_text_color(ui_PresetN, lv_color_hex(0xE1913B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetN, 240, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_PresetN, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_PresetN, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PresetN, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetN, &ui_font_radjSemi180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PresetN, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TopBarPanel = lv_obj_create(ui_Main);
    lv_obj_set_width(ui_TopBarPanel, 480);
    lv_obj_set_height(ui_TopBarPanel, 76);
    lv_obj_set_align(ui_TopBarPanel, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_TopBarPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TopBarPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TopBarPanel, lv_color_hex(0x181008), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TopBarPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TopBarPanel, lv_color_hex(0xB47D41), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TopBarPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TopBarPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OSC1Level = ui_BAR2_create(ui_TopBarPanel);
    lv_obj_set_width(ui_OSC1Level, 466);
    lv_obj_set_height(ui_OSC1Level, 16);
    lv_obj_set_x(ui_OSC1Level, 0);
    lv_obj_set_y(ui_OSC1Level, -24);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    ui_OSC2Level = ui_BAR2_create(ui_TopBarPanel);
    lv_obj_set_width(ui_OSC2Level, 466);
    lv_obj_set_height(ui_OSC2Level, 16);
    lv_obj_set_x(ui_OSC2Level, 0);
    lv_obj_set_y(ui_OSC2Level, 0);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    ui_SUBLevel = ui_BAR2_create(ui_TopBarPanel);
    lv_obj_set_width(ui_SUBLevel, 466);
    lv_obj_set_height(ui_SUBLevel, 16);
    lv_obj_set_x(ui_SUBLevel, 0);
    lv_obj_set_y(ui_SUBLevel, 24);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    ui_ADSRContainer = lv_obj_create(ui_Main);
    lv_obj_remove_style_all(ui_ADSRContainer);
    lv_obj_set_width(ui_ADSRContainer, 173);
    lv_obj_set_height(ui_ADSRContainer, 87);
    lv_obj_set_x(ui_ADSRContainer, 0);
    lv_obj_set_y(ui_ADSRContainer, 104);
    lv_obj_set_align(ui_ADSRContainer, LV_ALIGN_TOP_RIGHT);
    lv_obj_remove_flag(ui_ADSRContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ADSRContainer, lv_color_hex(0xB47D41), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ADSRContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ADSRContainer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ADSRContainer, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ADSR1AttackBar = lv_bar_create(ui_ADSRContainer);
    lv_bar_set_range(ui_ADSR1AttackBar, 0, 127);
    lv_bar_set_value(ui_ADSR1AttackBar, 99, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_ADSR1AttackBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_ADSR1AttackBar, 138);
    lv_obj_set_height(ui_ADSR1AttackBar, 14);
    lv_obj_set_x(ui_ADSR1AttackBar, -6);
    lv_obj_set_y(ui_ADSR1AttackBar, -68);
    lv_obj_set_align(ui_ADSR1AttackBar, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_remove_flag(ui_ADSR1AttackBar,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_radius(ui_ADSR1AttackBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ADSR1AttackBar, lv_color_hex(0xFF3B18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ADSR1AttackBar, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_ADSR1AttackBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_ADSR1AttackBar, 500, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ADSR1AttackBar, lv_color_hex(0xFF7430), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ADSR1AttackBar, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ADSR1AttackBar, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ADSR1AttackBar, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ADSR1AttackBar, lv_color_hex(0xFF3B18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ADSR1AttackBar, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ADSR1AttackBar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ADSR1AttackBar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_ADSR1AttackBar, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_ADSR1AttackBar, 1200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ADSR1AttackBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ADSR1AttackBar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ADSR1AttackBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ADSR1AttackBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ADSR1AttackBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ADSR1AttackBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_ADSR1AttackBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ADSR1AttackBar, lv_color_hex(0x3BE1AD), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ADSR1AttackBar, 220, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ADSR1AttackBar, lv_color_hex(0xFF3B18), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_ADSR1AttackBar, 50, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_ADSR1AttackBar, 500, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ADSR1AttackBar, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_ADSR1AttackBar, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ADSR1AttackBar, lv_color_hex(0xFF9C48), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ADSR1AttackBar, 100, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ADSR1AttackBar, 3, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ADSR1AttackBar, LV_BORDER_SIDE_TOP, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ADSR1AttackBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ADSR1AttackBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_ADSR1AttackBar, LV_BLEND_MODE_ADDITIVE, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_ADSR1AttackBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_ADSR1AttackBar, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_ADSR1AttackBar,
                                                                                                     lv_obj_get_style_pad_right(ui_ADSR1AttackBar, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_ADSR1DecayBar = lv_bar_create(ui_ADSRContainer);
    lv_bar_set_range(ui_ADSR1DecayBar, 0, 127);
    lv_bar_set_value(ui_ADSR1DecayBar, 99, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_ADSR1DecayBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_ADSR1DecayBar, 138);
    lv_obj_set_height(ui_ADSR1DecayBar, 14);
    lv_obj_set_x(ui_ADSR1DecayBar, -6);
    lv_obj_set_y(ui_ADSR1DecayBar, -47);
    lv_obj_set_align(ui_ADSR1DecayBar, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_remove_flag(ui_ADSR1DecayBar,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_radius(ui_ADSR1DecayBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ADSR1DecayBar, lv_color_hex(0xFF3B18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ADSR1DecayBar, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_ADSR1DecayBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_ADSR1DecayBar, 500, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ADSR1DecayBar, lv_color_hex(0xFF7430), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ADSR1DecayBar, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ADSR1DecayBar, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ADSR1DecayBar, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ADSR1DecayBar, lv_color_hex(0xFF3B18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ADSR1DecayBar, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ADSR1DecayBar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ADSR1DecayBar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_ADSR1DecayBar, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_ADSR1DecayBar, 1200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ADSR1DecayBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ADSR1DecayBar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ADSR1DecayBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ADSR1DecayBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ADSR1DecayBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ADSR1DecayBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_ADSR1DecayBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ADSR1DecayBar, lv_color_hex(0x3BE1AD), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ADSR1DecayBar, 220, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ADSR1DecayBar, lv_color_hex(0xFF3B18), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_ADSR1DecayBar, 50, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_ADSR1DecayBar, 500, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ADSR1DecayBar, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_ADSR1DecayBar, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ADSR1DecayBar, lv_color_hex(0xFF9C48), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ADSR1DecayBar, 100, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ADSR1DecayBar, 3, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ADSR1DecayBar, LV_BORDER_SIDE_TOP, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ADSR1DecayBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ADSR1DecayBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_ADSR1DecayBar, LV_BLEND_MODE_ADDITIVE, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_ADSR1DecayBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_ADSR1DecayBar, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_ADSR1DecayBar,
                                                                                                    lv_obj_get_style_pad_right(ui_ADSR1DecayBar, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_ADSR1SustainBar = lv_bar_create(ui_ADSRContainer);
    lv_bar_set_range(ui_ADSR1SustainBar, 0, 127);
    lv_bar_set_value(ui_ADSR1SustainBar, 99, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_ADSR1SustainBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_ADSR1SustainBar, 138);
    lv_obj_set_height(ui_ADSR1SustainBar, 14);
    lv_obj_set_x(ui_ADSR1SustainBar, -6);
    lv_obj_set_y(ui_ADSR1SustainBar, -26);
    lv_obj_set_align(ui_ADSR1SustainBar, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_remove_flag(ui_ADSR1SustainBar,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_radius(ui_ADSR1SustainBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ADSR1SustainBar, lv_color_hex(0xFF3B18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ADSR1SustainBar, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_ADSR1SustainBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_ADSR1SustainBar, 500, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ADSR1SustainBar, lv_color_hex(0xFF7430), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ADSR1SustainBar, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ADSR1SustainBar, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ADSR1SustainBar, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ADSR1SustainBar, lv_color_hex(0xFF3B18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ADSR1SustainBar, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ADSR1SustainBar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ADSR1SustainBar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_ADSR1SustainBar, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_ADSR1SustainBar, 1200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ADSR1SustainBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ADSR1SustainBar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ADSR1SustainBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ADSR1SustainBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ADSR1SustainBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ADSR1SustainBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_ADSR1SustainBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ADSR1SustainBar, lv_color_hex(0x3BE1AD), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ADSR1SustainBar, 220, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ADSR1SustainBar, lv_color_hex(0xFF3B18), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_ADSR1SustainBar, 50, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_ADSR1SustainBar, 500, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ADSR1SustainBar, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_ADSR1SustainBar, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ADSR1SustainBar, lv_color_hex(0xFF9C48), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ADSR1SustainBar, 100, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ADSR1SustainBar, 3, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ADSR1SustainBar, LV_BORDER_SIDE_TOP, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ADSR1SustainBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ADSR1SustainBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_ADSR1SustainBar, LV_BLEND_MODE_ADDITIVE, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_ADSR1SustainBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_ADSR1SustainBar, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_ADSR1SustainBar,
                                                                                                      lv_obj_get_style_pad_right(ui_ADSR1SustainBar, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_ADSR1ReleaseBar = lv_bar_create(ui_ADSRContainer);
    lv_bar_set_range(ui_ADSR1ReleaseBar, 0, 127);
    lv_bar_set_value(ui_ADSR1ReleaseBar, 99, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_ADSR1ReleaseBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_ADSR1ReleaseBar, 138);
    lv_obj_set_height(ui_ADSR1ReleaseBar, 14);
    lv_obj_set_x(ui_ADSR1ReleaseBar, -6);
    lv_obj_set_y(ui_ADSR1ReleaseBar, -5);
    lv_obj_set_align(ui_ADSR1ReleaseBar, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_remove_flag(ui_ADSR1ReleaseBar,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_radius(ui_ADSR1ReleaseBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ADSR1ReleaseBar, lv_color_hex(0xFF3B18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ADSR1ReleaseBar, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_ADSR1ReleaseBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_ADSR1ReleaseBar, 500, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ADSR1ReleaseBar, lv_color_hex(0xFF7430), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ADSR1ReleaseBar, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ADSR1ReleaseBar, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ADSR1ReleaseBar, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ADSR1ReleaseBar, lv_color_hex(0xFF3B18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ADSR1ReleaseBar, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ADSR1ReleaseBar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ADSR1ReleaseBar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_ADSR1ReleaseBar, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_ADSR1ReleaseBar, 1200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ADSR1ReleaseBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ADSR1ReleaseBar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ADSR1ReleaseBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ADSR1ReleaseBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ADSR1ReleaseBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ADSR1ReleaseBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_ADSR1ReleaseBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ADSR1ReleaseBar, lv_color_hex(0x3BE1AD), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ADSR1ReleaseBar, 220, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ADSR1ReleaseBar, lv_color_hex(0xFF3B18), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_ADSR1ReleaseBar, 50, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_ADSR1ReleaseBar, 500, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ADSR1ReleaseBar, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_ADSR1ReleaseBar, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ADSR1ReleaseBar, lv_color_hex(0xFF9C48), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ADSR1ReleaseBar, 100, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ADSR1ReleaseBar, 3, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ADSR1ReleaseBar, LV_BORDER_SIDE_TOP, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ADSR1ReleaseBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ADSR1ReleaseBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_ADSR1ReleaseBar, LV_BLEND_MODE_ADDITIVE, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_ADSR1ReleaseBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_ADSR1ReleaseBar, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_ADSR1ReleaseBar,
                                                                                                      lv_obj_get_style_pad_right(ui_ADSR1ReleaseBar, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Label9 = lv_label_create(ui_ADSRContainer);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 6);
    lv_obj_set_y(ui_Label9, 1);
    lv_label_set_text(ui_Label9, "A");
    lv_obj_set_style_text_font(ui_Label9, &ui_font_Square22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_ADSRContainer);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 6);
    lv_obj_set_y(ui_Label10, 22);
    lv_label_set_text(ui_Label10, "D");
    lv_obj_set_style_text_font(ui_Label10, &ui_font_Square22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_ADSRContainer);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 6);
    lv_obj_set_y(ui_Label11, 43);
    lv_label_set_text(ui_Label11, "S");
    lv_obj_set_style_text_font(ui_Label11, &ui_font_Square22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_ADSRContainer);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 6);
    lv_obj_set_y(ui_Label12, 64);
    lv_label_set_text(ui_Label12, "R");
    lv_obj_set_style_text_font(ui_Label12, &ui_font_Square22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ADSRContainer1 = lv_obj_create(ui_Main);
    lv_obj_remove_style_all(ui_ADSRContainer1);
    lv_obj_set_width(ui_ADSRContainer1, 173);
    lv_obj_set_height(ui_ADSRContainer1, 87);
    lv_obj_set_x(ui_ADSRContainer1, 0);
    lv_obj_set_y(ui_ADSRContainer1, 190);
    lv_obj_set_align(ui_ADSRContainer1, LV_ALIGN_TOP_RIGHT);
    lv_obj_remove_flag(ui_ADSRContainer1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ADSRContainer1, lv_color_hex(0xB47D41), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ADSRContainer1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ADSRContainer1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ADSRContainer1, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ADSR2AttackBar = lv_bar_create(ui_ADSRContainer1);
    lv_bar_set_range(ui_ADSR2AttackBar, 0, 127);
    lv_bar_set_value(ui_ADSR2AttackBar, 99, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_ADSR2AttackBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_ADSR2AttackBar, 138);
    lv_obj_set_height(ui_ADSR2AttackBar, 14);
    lv_obj_set_x(ui_ADSR2AttackBar, -6);
    lv_obj_set_y(ui_ADSR2AttackBar, -68);
    lv_obj_set_align(ui_ADSR2AttackBar, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_remove_flag(ui_ADSR2AttackBar,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_radius(ui_ADSR2AttackBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ADSR2AttackBar, lv_color_hex(0xFF187C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ADSR2AttackBar, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_ADSR2AttackBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_ADSR2AttackBar, 500, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ADSR2AttackBar, lv_color_hex(0xFF7430), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ADSR2AttackBar, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ADSR2AttackBar, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ADSR2AttackBar, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ADSR2AttackBar, lv_color_hex(0xFF3B18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ADSR2AttackBar, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ADSR2AttackBar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ADSR2AttackBar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_ADSR2AttackBar, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_ADSR2AttackBar, 1200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ADSR2AttackBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ADSR2AttackBar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ADSR2AttackBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ADSR2AttackBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ADSR2AttackBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ADSR2AttackBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_ADSR2AttackBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ADSR2AttackBar, lv_color_hex(0xD3E13B), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ADSR2AttackBar, 220, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ADSR2AttackBar, lv_color_hex(0xFF187C), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_ADSR2AttackBar, 50, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_ADSR2AttackBar, 500, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ADSR2AttackBar, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_ADSR2AttackBar, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ADSR2AttackBar, lv_color_hex(0xFF9C48), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ADSR2AttackBar, 100, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ADSR2AttackBar, 3, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ADSR2AttackBar, LV_BORDER_SIDE_TOP, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ADSR2AttackBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ADSR2AttackBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_ADSR2AttackBar, LV_BLEND_MODE_ADDITIVE, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_ADSR2AttackBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_ADSR2AttackBar, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_ADSR2AttackBar,
                                                                                                     lv_obj_get_style_pad_right(ui_ADSR2AttackBar, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_ADSR2DecayBar = lv_bar_create(ui_ADSRContainer1);
    lv_bar_set_range(ui_ADSR2DecayBar, 0, 127);
    lv_bar_set_value(ui_ADSR2DecayBar, 99, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_ADSR2DecayBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_ADSR2DecayBar, 138);
    lv_obj_set_height(ui_ADSR2DecayBar, 14);
    lv_obj_set_x(ui_ADSR2DecayBar, -6);
    lv_obj_set_y(ui_ADSR2DecayBar, -47);
    lv_obj_set_align(ui_ADSR2DecayBar, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_remove_flag(ui_ADSR2DecayBar,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_radius(ui_ADSR2DecayBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ADSR2DecayBar, lv_color_hex(0xFF187C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ADSR2DecayBar, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_ADSR2DecayBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_ADSR2DecayBar, 500, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ADSR2DecayBar, lv_color_hex(0xFF7430), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ADSR2DecayBar, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ADSR2DecayBar, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ADSR2DecayBar, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ADSR2DecayBar, lv_color_hex(0xFF3B18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ADSR2DecayBar, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ADSR2DecayBar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ADSR2DecayBar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_ADSR2DecayBar, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_ADSR2DecayBar, 1200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ADSR2DecayBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ADSR2DecayBar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ADSR2DecayBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ADSR2DecayBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ADSR2DecayBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ADSR2DecayBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_ADSR2DecayBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ADSR2DecayBar, lv_color_hex(0xD3E13B), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ADSR2DecayBar, 220, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ADSR2DecayBar, lv_color_hex(0xFF187C), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_ADSR2DecayBar, 50, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_ADSR2DecayBar, 500, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ADSR2DecayBar, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_ADSR2DecayBar, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ADSR2DecayBar, lv_color_hex(0xFF9C48), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ADSR2DecayBar, 100, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ADSR2DecayBar, 3, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ADSR2DecayBar, LV_BORDER_SIDE_TOP, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ADSR2DecayBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ADSR2DecayBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_ADSR2DecayBar, LV_BLEND_MODE_ADDITIVE, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_ADSR2DecayBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_ADSR2DecayBar, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_ADSR2DecayBar,
                                                                                                    lv_obj_get_style_pad_right(ui_ADSR2DecayBar, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_ADSR2SustainBar = lv_bar_create(ui_ADSRContainer1);
    lv_bar_set_range(ui_ADSR2SustainBar, 0, 127);
    lv_bar_set_value(ui_ADSR2SustainBar, 99, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_ADSR2SustainBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_ADSR2SustainBar, 138);
    lv_obj_set_height(ui_ADSR2SustainBar, 14);
    lv_obj_set_x(ui_ADSR2SustainBar, -6);
    lv_obj_set_y(ui_ADSR2SustainBar, -26);
    lv_obj_set_align(ui_ADSR2SustainBar, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_remove_flag(ui_ADSR2SustainBar,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_radius(ui_ADSR2SustainBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ADSR2SustainBar, lv_color_hex(0xFF187C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ADSR2SustainBar, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_ADSR2SustainBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_ADSR2SustainBar, 500, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ADSR2SustainBar, lv_color_hex(0xFF7430), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ADSR2SustainBar, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ADSR2SustainBar, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ADSR2SustainBar, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ADSR2SustainBar, lv_color_hex(0xFF3B18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ADSR2SustainBar, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ADSR2SustainBar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ADSR2SustainBar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_ADSR2SustainBar, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_ADSR2SustainBar, 1200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ADSR2SustainBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ADSR2SustainBar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ADSR2SustainBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ADSR2SustainBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ADSR2SustainBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ADSR2SustainBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_ADSR2SustainBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ADSR2SustainBar, lv_color_hex(0xD3E13B), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ADSR2SustainBar, 220, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ADSR2SustainBar, lv_color_hex(0xFF187C), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_ADSR2SustainBar, 50, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_ADSR2SustainBar, 500, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ADSR2SustainBar, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_ADSR2SustainBar, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ADSR2SustainBar, lv_color_hex(0xFF9C48), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ADSR2SustainBar, 100, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ADSR2SustainBar, 3, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ADSR2SustainBar, LV_BORDER_SIDE_TOP, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ADSR2SustainBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ADSR2SustainBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_ADSR2SustainBar, LV_BLEND_MODE_ADDITIVE, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_ADSR2SustainBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_ADSR2SustainBar, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_ADSR2SustainBar,
                                                                                                      lv_obj_get_style_pad_right(ui_ADSR2SustainBar, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_ADSR2ReleaseBar = lv_bar_create(ui_ADSRContainer1);
    lv_bar_set_range(ui_ADSR2ReleaseBar, 0, 127);
    lv_bar_set_value(ui_ADSR2ReleaseBar, 99, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_ADSR2ReleaseBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_ADSR2ReleaseBar, 138);
    lv_obj_set_height(ui_ADSR2ReleaseBar, 14);
    lv_obj_set_x(ui_ADSR2ReleaseBar, -6);
    lv_obj_set_y(ui_ADSR2ReleaseBar, -5);
    lv_obj_set_align(ui_ADSR2ReleaseBar, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_remove_flag(ui_ADSR2ReleaseBar,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_radius(ui_ADSR2ReleaseBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ADSR2ReleaseBar, lv_color_hex(0xFF187C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ADSR2ReleaseBar, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_ADSR2ReleaseBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_ADSR2ReleaseBar, 500, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ADSR2ReleaseBar, lv_color_hex(0xFF7430), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ADSR2ReleaseBar, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ADSR2ReleaseBar, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ADSR2ReleaseBar, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ADSR2ReleaseBar, lv_color_hex(0xFF3B18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ADSR2ReleaseBar, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ADSR2ReleaseBar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ADSR2ReleaseBar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_ADSR2ReleaseBar, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_ADSR2ReleaseBar, 1200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ADSR2ReleaseBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ADSR2ReleaseBar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ADSR2ReleaseBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ADSR2ReleaseBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ADSR2ReleaseBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ADSR2ReleaseBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_ADSR2ReleaseBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ADSR2ReleaseBar, lv_color_hex(0xD3E13B), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ADSR2ReleaseBar, 220, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ADSR2ReleaseBar, lv_color_hex(0xFF187C), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_ADSR2ReleaseBar, 50, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_ADSR2ReleaseBar, 500, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ADSR2ReleaseBar, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_ADSR2ReleaseBar, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ADSR2ReleaseBar, lv_color_hex(0xFF9C48), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ADSR2ReleaseBar, 100, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ADSR2ReleaseBar, 3, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ADSR2ReleaseBar, LV_BORDER_SIDE_TOP, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ADSR2ReleaseBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ADSR2ReleaseBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_ADSR2ReleaseBar, LV_BLEND_MODE_ADDITIVE, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_ADSR2ReleaseBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_ADSR2ReleaseBar, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_ADSR2ReleaseBar,
                                                                                                      lv_obj_get_style_pad_right(ui_ADSR2ReleaseBar, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Label13 = lv_label_create(ui_ADSRContainer1);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 6);
    lv_obj_set_y(ui_Label13, 1);
    lv_label_set_text(ui_Label13, "A");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0xFF3B18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &ui_font_Square22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_ADSRContainer1);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 6);
    lv_obj_set_y(ui_Label14, 22);
    lv_label_set_text(ui_Label14, "D");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0xFF3B18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &ui_font_Square22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_ADSRContainer1);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 6);
    lv_obj_set_y(ui_Label15, 43);
    lv_label_set_text(ui_Label15, "S");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0xFF3B18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label15, &ui_font_Square22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_ADSRContainer1);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, 6);
    lv_obj_set_y(ui_Label16, 64);
    lv_label_set_text(ui_Label16, "R");
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0xFF3B18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label16, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &ui_font_Square22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetNamePanel = lv_obj_create(ui_Main);
    lv_obj_set_width(ui_PresetNamePanel, 480);
    lv_obj_set_height(ui_PresetNamePanel, 29);
    lv_obj_set_x(ui_PresetNamePanel, 0);
    lv_obj_set_y(ui_PresetNamePanel, -70);
    lv_obj_set_align(ui_PresetNamePanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PresetNamePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PresetNamePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PresetNamePanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PresetNamePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PresetNamePanel, lv_color_hex(0xAC7939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PresetNamePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PresetNamePanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BottomContainer = lv_obj_create(ui_Main);
    lv_obj_remove_style_all(ui_BottomContainer);
    lv_obj_set_width(ui_BottomContainer, 480);
    lv_obj_set_height(ui_BottomContainer, 44);
    lv_obj_set_align(ui_BottomContainer, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_BottomContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_BottomContainer, lv_color_hex(0xB47D41), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BottomContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BottomContainer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_BottomContainer, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetNameShadow = lv_label_create(ui_BottomContainer);
    lv_obj_set_width(ui_PresetNameShadow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PresetNameShadow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PresetNameShadow, 9);
    lv_obj_set_y(ui_PresetNameShadow, 5);
    lv_label_set_text(ui_PresetNameShadow, "Preset Name");
    lv_obj_set_style_text_color(ui_PresetNameShadow, lv_color_hex(0xEA4900), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetNameShadow, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetNameShadow, &ui_font_radjMed38, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PresetNameShadow, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetName = lv_label_create(ui_BottomContainer);
    lv_obj_set_width(ui_PresetName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PresetName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PresetName, 11);
    lv_obj_set_y(ui_PresetName, 2);
    lv_label_set_text(ui_PresetName, "Preset Name");
    lv_obj_set_style_text_color(ui_PresetName, lv_color_hex(0xC48A30), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetName, &ui_font_radjMed38, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PresetName, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BottomMessagePanel = lv_obj_create(ui_BottomContainer);
    lv_obj_set_width(ui_BottomMessagePanel, 478);
    lv_obj_set_height(ui_BottomMessagePanel, 35);
    lv_obj_set_x(ui_BottomMessagePanel, 0);
    lv_obj_set_y(ui_BottomMessagePanel, -2);
    lv_obj_set_align(ui_BottomMessagePanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BottomMessagePanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_BottomMessagePanel,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_BottomMessagePanel, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_BottomMessagePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BottomMessagePanel, lv_color_hex(0xFF4200), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BottomMessagePanel, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_BottomMessagePanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_BottomMessagePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_BottomMessagePanel, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_BottomMessagePanel, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BottomMessagePanel, lv_color_hex(0xFF5700), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BottomMessagePanel, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BottomMessagePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_BottomMessagePanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_BottomMessagePanel, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_BottomMessagePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CommandMessageShadow = lv_label_create(ui_BottomMessagePanel);
    lv_obj_set_width(ui_CommandMessageShadow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CommandMessageShadow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CommandMessageShadow, -7);
    lv_obj_set_y(ui_CommandMessageShadow, -9);
    lv_label_set_text(ui_CommandMessageShadow, "COMMAND MESSAGES");
    lv_obj_set_style_text_color(ui_CommandMessageShadow, lv_color_hex(0xFF3B18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CommandMessageShadow, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_CommandMessageShadow, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CommandMessageShadow, &ui_font_square32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CommandMessage = lv_label_create(ui_BottomMessagePanel);
    lv_obj_set_width(ui_CommandMessage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CommandMessage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CommandMessage, -5);
    lv_obj_set_y(ui_CommandMessage, -11);
    lv_label_set_text(ui_CommandMessage, "COMMAND MESSAGES");
    lv_obj_set_style_text_color(ui_CommandMessage, lv_color_hex(0xE1913B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CommandMessage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_CommandMessage, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CommandMessage, &ui_font_square32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_CommandMessage, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CommandValueShadow = lv_label_create(ui_BottomMessagePanel);
    lv_obj_set_width(ui_CommandValueShadow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CommandValueShadow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CommandValueShadow, 395);
    lv_obj_set_y(ui_CommandValueShadow, -9);
    lv_label_set_text(ui_CommandValueShadow, "127");
    lv_obj_set_style_text_color(ui_CommandValueShadow, lv_color_hex(0xFF3B18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CommandValueShadow, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_CommandValueShadow, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CommandValueShadow, &ui_font_square32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CommandValue = lv_label_create(ui_BottomMessagePanel);
    lv_obj_set_width(ui_CommandValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CommandValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CommandValue, 393);
    lv_obj_set_y(ui_CommandValue, -11);
    lv_label_set_text(ui_CommandValue, "127");
    lv_obj_set_style_text_color(ui_CommandValue, lv_color_hex(0xE1913B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CommandValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_CommandValue, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CommandValue, &ui_font_square32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetSavePanel = lv_obj_create(ui_Main);
    lv_obj_set_width(ui_PresetSavePanel, 296);
    lv_obj_set_height(ui_PresetSavePanel, 216);
    lv_obj_set_x(ui_PresetSavePanel, 0);
    lv_obj_set_y(ui_PresetSavePanel, -1);
    lv_obj_set_align(ui_PresetSavePanel, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_PresetSavePanel, LV_STATE_USER_1);       /// States
    lv_obj_add_flag(ui_PresetSavePanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_PresetSavePanel,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_PresetSavePanel, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_PresetSavePanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PresetSavePanel, lv_color_hex(0x831918), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PresetSavePanel, 220, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PresetSavePanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PresetSavePanel, lv_color_hex(0x810202), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_PresetSavePanel, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_PresetSavePanel, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_PresetSavePanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PresetSavePanel, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetSaveFromTitleShadow = lv_label_create(ui_PresetSavePanel);
    lv_obj_set_width(ui_PresetSaveFromTitleShadow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PresetSaveFromTitleShadow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PresetSaveFromTitleShadow, -6);
    lv_obj_set_y(ui_PresetSaveFromTitleShadow, -10);
    lv_label_set_text(ui_PresetSaveFromTitleShadow, "Saving FROM:");
    lv_obj_set_style_text_color(ui_PresetSaveFromTitleShadow, lv_color_hex(0xE55E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetSaveFromTitleShadow, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetSaveFromTitleShadow, &ui_font_Square22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PresetSaveFromTitleShadow, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetSaveFromTitle = lv_label_create(ui_PresetSavePanel);
    lv_obj_set_width(ui_PresetSaveFromTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PresetSaveFromTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PresetSaveFromTitle, -4);
    lv_obj_set_y(ui_PresetSaveFromTitle, -7);
    lv_label_set_text(ui_PresetSaveFromTitle, "Saving FROM:");
    lv_obj_set_style_text_color(ui_PresetSaveFromTitle, lv_color_hex(0xE55E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetSaveFromTitle, 240, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetSaveFromTitle, &ui_font_Square22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PresetSaveFromTitle, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetNOLDShadow = lv_label_create(ui_PresetSavePanel);
    lv_obj_set_width(ui_PresetNOLDShadow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PresetNOLDShadow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PresetNOLDShadow, 70);
    lv_obj_set_y(ui_PresetNOLDShadow, -85);
    lv_obj_set_align(ui_PresetNOLDShadow, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PresetNOLDShadow, "208");
    lv_obj_set_style_text_color(ui_PresetNOLDShadow, lv_color_hex(0xE55E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetNOLDShadow, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_PresetNOLDShadow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_PresetNOLDShadow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PresetNOLDShadow, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetNOLDShadow, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PresetNOLDShadow, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetNOLD = lv_label_create(ui_PresetSavePanel);
    lv_obj_set_width(ui_PresetNOLD, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PresetNOLD, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PresetNOLD, 74);
    lv_obj_set_y(ui_PresetNOLD, -84);
    lv_obj_set_align(ui_PresetNOLD, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PresetNOLD, "208");
    lv_obj_set_style_text_color(ui_PresetNOLD, lv_color_hex(0xE55E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetNOLD, 230, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_PresetNOLD, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_PresetNOLD, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PresetNOLD, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetNOLD, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PresetNOLD, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetNameOLDShadow = lv_label_create(ui_PresetSavePanel);
    lv_obj_set_width(ui_PresetNameOLDShadow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PresetNameOLDShadow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PresetNameOLDShadow, 37);
    lv_obj_set_y(ui_PresetNameOLDShadow, 35);
    lv_label_set_text(ui_PresetNameOLDShadow, "PRESET NAME");
    lv_obj_set_style_text_color(ui_PresetNameOLDShadow, lv_color_hex(0xE55E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetNameOLDShadow, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetNameOLDShadow, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PresetNameOLDShadow, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetNameOLD = lv_label_create(ui_PresetSavePanel);
    lv_obj_set_width(ui_PresetNameOLD, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PresetNameOLD, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PresetNameOLD, 40);
    lv_obj_set_y(ui_PresetNameOLD, 37);
    lv_label_set_text(ui_PresetNameOLD, "PRESET NAME");
    lv_obj_set_style_text_color(ui_PresetNameOLD, lv_color_hex(0xE55E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetNameOLD, 240, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetNameOLD, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PresetNameOLD, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetSaveToShadow = lv_label_create(ui_PresetSavePanel);
    lv_obj_set_width(ui_PresetSaveToShadow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PresetSaveToShadow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PresetSaveToShadow, -10);
    lv_obj_set_y(ui_PresetSaveToShadow, 76);
    lv_label_set_text(ui_PresetSaveToShadow, "TO:");
    lv_obj_set_style_text_color(ui_PresetSaveToShadow, lv_color_hex(0xE55E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetSaveToShadow, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetSaveToShadow, &ui_font_Square22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PresetSaveToShadow, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetSaveTo = lv_label_create(ui_PresetSavePanel);
    lv_obj_set_width(ui_PresetSaveTo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PresetSaveTo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PresetSaveTo, -6);
    lv_obj_set_y(ui_PresetSaveTo, 79);
    lv_label_set_text(ui_PresetSaveTo, "TO:");
    lv_obj_set_style_text_color(ui_PresetSaveTo, lv_color_hex(0xE55E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetSaveTo, 240, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetSaveTo, &ui_font_Square22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PresetSaveTo, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetNNewShadow = lv_label_create(ui_PresetSavePanel);
    lv_obj_set_width(ui_PresetNNewShadow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PresetNNewShadow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PresetNNewShadow, 68);
    lv_obj_set_y(ui_PresetNNewShadow, 17);
    lv_obj_set_align(ui_PresetNNewShadow, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PresetNNewShadow, "208");
    lv_obj_set_style_text_color(ui_PresetNNewShadow, lv_color_hex(0xE55E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetNNewShadow, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_PresetNNewShadow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_PresetNNewShadow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PresetNNewShadow, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetNNewShadow, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PresetNNewShadow, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetNNew = lv_label_create(ui_PresetSavePanel);
    lv_obj_set_width(ui_PresetNNew, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PresetNNew, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PresetNNew, 72);
    lv_obj_set_y(ui_PresetNNew, 18);
    lv_obj_set_align(ui_PresetNNew, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PresetNNew, "208");
    lv_obj_set_style_text_color(ui_PresetNNew, lv_color_hex(0xE55E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetNNew, 230, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_PresetNNew, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_PresetNNew, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PresetNNew, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetNNew, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PresetNNew, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetNameNew = lv_label_create(ui_PresetSavePanel);
    lv_obj_set_width(ui_PresetNameNew, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PresetNameNew, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PresetNameNew, 40);
    lv_obj_set_y(ui_PresetNameNew, 145);
    lv_label_set_text(ui_PresetNameNew, "PRESET NAME");
    lv_obj_set_style_text_color(ui_PresetNameNew, lv_color_hex(0xE55E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetNameNew, 240, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetNameNew, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PresetNameNew, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetNameNewShadow = lv_label_create(ui_PresetSavePanel);
    lv_obj_set_width(ui_PresetNameNewShadow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PresetNameNewShadow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PresetNameNewShadow, 37);
    lv_obj_set_y(ui_PresetNameNewShadow, 142);
    lv_label_set_text(ui_PresetNameNewShadow, "PRESET NAME");
    lv_obj_set_style_text_color(ui_PresetNameNewShadow, lv_color_hex(0xE55E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetNameNewShadow, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetNameNewShadow, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PresetNameNewShadow, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetNewName = lv_textarea_create(ui_Main);
    lv_obj_set_width(ui_PresetNewName, 255);
    lv_obj_set_height(ui_PresetNewName, LV_SIZE_CONTENT);    /// 51
    lv_obj_set_x(ui_PresetNewName, 4);
    lv_obj_set_y(ui_PresetNewName, 54);
    lv_obj_set_align(ui_PresetNewName, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_PresetNewName, 12);
    lv_textarea_set_one_line(ui_PresetNewName, true);
    lv_obj_add_state(ui_PresetNewName, LV_STATE_FOCUSED);       /// States
    lv_obj_add_flag(ui_PresetNewName, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_WITH_ARROW);     /// Flags
    lv_obj_remove_flag(ui_PresetNewName,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_PresetNewName, lv_color_hex(0x8C0E0E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetNewName, 240, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PresetNewName, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetNewName, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PresetNewName, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PresetNewName, lv_color_hex(0xF51419), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PresetNewName, 210, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_PresetNewName, lv_color_hex(0xFFAF2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PresetNewName, lv_color_hex(0x050000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PresetNewName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PresetNewName, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PresetNewName, lv_color_hex(0xFF0C00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_PresetNewName, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_PresetNewName, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_PresetNewName, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_PresetNewName, lv_color_hex(0x1D0101), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetNewName, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PresetNewName, lv_color_hex(0xE50B00), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PresetNewName, 160, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PresetNewName, LV_BLEND_MODE_ADDITIVE, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_PresetNewName, lv_color_hex(0xFF1A15), LV_PART_CURSOR | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_PresetNewName, 220, LV_PART_CURSOR | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_PresetNewName, lv_color_hex(0x7C1515), LV_PART_CURSOR | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_PresetNewName, 255, LV_PART_CURSOR | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_PresetNewName, lv_color_hex(0xFF0000), LV_PART_CURSOR | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_PresetNewName, 150, LV_PART_CURSOR | LV_STATE_FOCUSED);

    ui_PresetSavedMesage = lv_textarea_create(ui_Main);
    lv_obj_set_width(ui_PresetSavedMesage, 253);
    lv_obj_set_height(ui_PresetSavedMesage, 51);
    lv_obj_set_x(ui_PresetSavedMesage, 3);
    lv_obj_set_y(ui_PresetSavedMesage, 12);
    lv_obj_set_align(ui_PresetSavedMesage, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_PresetSavedMesage, "PRESET SAVED");
    lv_obj_add_flag(ui_PresetSavedMesage, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_PresetSavedMesage, lv_color_hex(0xFFB131), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetSavedMesage, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PresetSavedMesage, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetSavedMesage, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PresetSavedMesage, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PresetSavedMesage, lv_color_hex(0xF51419), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PresetSavedMesage, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_PresetSavedMesage, LV_GRAD_DIR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PresetSavedMesage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PresetSavedMesage, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PresetSavedMesage, lv_color_hex(0xFF0C00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_PresetSavedMesage, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_PresetSavedMesage, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_PresetSavedMesage, 30, LV_PART_MAIN | LV_STATE_DEFAULT);



}
