// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: DCO_v4_ILI9488

#include "ui.h"

void ui_MANUALCALIBRATION_screen_init(void)
{
    ui_MANUALCALIBRATION = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_MANUALCALIBRATION, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MANUALCALIBRATION, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MANUALCALIBRATION, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_MANUALCALIBRATION, lv_color_hex(0xE1913B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MANUALCALIBRATION, 240, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MANUALCALIBRATION, &ui_font_radj22SEMI, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_calibrationTabs = lv_tabview_create(ui_MANUALCALIBRATION);
    lv_tabview_set_tab_bar_position(ui_calibrationTabs, LV_DIR_LEFT);
    lv_tabview_set_tab_bar_size(ui_calibrationTabs, 320);
    lv_obj_set_width(ui_calibrationTabs, 320);
    lv_obj_set_height(ui_calibrationTabs, 240);
    lv_obj_set_align(ui_calibrationTabs, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_calibrationTabs, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_align(ui_calibrationTabs, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_calibrationTabs, lv_color_hex(0x00FF35), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_calibrationTabs, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_calibrationTabs, lv_color_hex(0x00FF5D), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_calibrationTabs, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_set_style_text_color(lv_tabview_get_tab_bar(ui_calibrationTabs), lv_color_hex(0xD4D4D4),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_tabview_get_tab_bar(ui_calibrationTabs), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(lv_tabview_get_tab_bar(ui_calibrationTabs), LV_TEXT_ALIGN_LEFT,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_tabview_get_tab_bar(ui_calibrationTabs), &lv_font_montserrat_22,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_tabview_get_tab_bar(ui_calibrationTabs), lv_color_hex(0x000000),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_bar(ui_calibrationTabs), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(lv_tabview_get_tab_bar(ui_calibrationTabs), lv_color_hex(0xA51A1A),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(lv_tabview_get_tab_bar(ui_calibrationTabs), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(lv_tabview_get_tab_bar(ui_calibrationTabs), 2,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(lv_tabview_get_tab_bar(ui_calibrationTabs), LV_BORDER_SIDE_FULL,
                                 LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(lv_tabview_get_tab_bar(ui_calibrationTabs), lv_color_hex(0x09FF00),
                                LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(lv_tabview_get_tab_bar(ui_calibrationTabs), 255,  LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(lv_tabview_get_tab_bar(ui_calibrationTabs), lv_color_hex(0x00FF0C),
                                LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(lv_tabview_get_tab_bar(ui_calibrationTabs), 255,  LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_set_style_text_align(lv_tabview_get_tab_bar(ui_calibrationTabs), LV_TEXT_ALIGN_LEFT,
                                LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(lv_tabview_get_tab_bar(ui_calibrationTabs), lv_color_hex(0x00FF64),
                                LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(lv_tabview_get_tab_bar(ui_calibrationTabs), 255,  LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(lv_tabview_get_tab_bar(ui_calibrationTabs), lv_color_hex(0x00FF27),
                                LV_PART_ITEMS | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(lv_tabview_get_tab_bar(ui_calibrationTabs), 255,  LV_PART_ITEMS | LV_STATE_FOCUSED);

    ui_autoCalibrationPage = lv_tabview_add_tab(ui_calibrationTabs, "- AUTO CALIBRATION");

    ui_PWCalibrationPage = lv_tabview_add_tab(ui_calibrationTabs, "- PW CALIBRATION");

    ui_fullCalibrationPage = lv_tabview_add_tab(ui_calibrationTabs, "- FULL CALIBRATION");

    ui_manualCalibrationPage = lv_tabview_add_tab(ui_calibrationTabs, "- MANUAL CALIBRATION");

    ui_manualCalibrationPanel = lv_obj_create(ui_MANUALCALIBRATION);
    lv_obj_set_width(ui_manualCalibrationPanel, 296);
    lv_obj_set_height(ui_manualCalibrationPanel, 216);
    lv_obj_set_align(ui_manualCalibrationPanel, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_manualCalibrationPanel, LV_STATE_USER_1);       /// States
    lv_obj_add_flag(ui_manualCalibrationPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_manualCalibrationPanel,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_manualCalibrationPanel, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_manualCalibrationPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_manualCalibrationPanel, lv_color_hex(0x831918), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_manualCalibrationPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_manualCalibrationPanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_manualCalibrationPanel, lv_color_hex(0x810202), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_manualCalibrationPanel, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_manualCalibrationPanel, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_manualCalibrationPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_manualCalibrationPanel, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DCONTITLE = lv_obj_create(ui_manualCalibrationPanel);
    lv_obj_remove_style_all(ui_DCONTITLE);
    lv_obj_set_width(ui_DCONTITLE, 128);
    lv_obj_set_height(ui_DCONTITLE, 22);
    lv_obj_set_x(ui_DCONTITLE, -66);
    lv_obj_set_y(ui_DCONTITLE, -82);
    lv_obj_set_align(ui_DCONTITLE, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DCONTITLE, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_oscillatorNTitleShadow = lv_label_create(ui_DCONTITLE);
    lv_obj_set_width(ui_oscillatorNTitleShadow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_oscillatorNTitleShadow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_oscillatorNTitleShadow, -3);
    lv_obj_set_y(ui_oscillatorNTitleShadow, -2);
    lv_label_set_text(ui_oscillatorNTitleShadow, "OSCILLATOR:");
    lv_obj_set_style_text_color(ui_oscillatorNTitleShadow, lv_color_hex(0xE55E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_oscillatorNTitleShadow, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_oscillatorNTitleShadow, &ui_font_Square22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_oscillatorNTitleShadow, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_oscillatorNTitle = lv_label_create(ui_DCONTITLE);
    lv_obj_set_width(ui_oscillatorNTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_oscillatorNTitle, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_oscillatorNTitle, "OSCILLATOR:\n");
    lv_obj_set_style_text_color(ui_oscillatorNTitle, lv_color_hex(0xE55E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_oscillatorNTitle, 240, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_oscillatorNTitle, &ui_font_Square22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_oscillatorNTitle, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DCON = lv_obj_create(ui_manualCalibrationPanel);
    lv_obj_remove_style_all(ui_DCON);
    lv_obj_set_width(ui_DCON, 100);
    lv_obj_set_height(ui_DCON, 50);
    lv_obj_set_x(ui_DCON, 61);
    lv_obj_set_y(ui_DCON, -84);
    lv_obj_set_align(ui_DCON, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DCON, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_oscillatorNShadow = lv_label_create(ui_DCON);
    lv_obj_set_width(ui_oscillatorNShadow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_oscillatorNShadow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_oscillatorNShadow, -4);
    lv_obj_set_y(ui_oscillatorNShadow, -1);
    lv_obj_set_align(ui_oscillatorNShadow, LV_ALIGN_CENTER);
    lv_label_set_text(ui_oscillatorNShadow, "208");
    lv_obj_set_style_text_color(ui_oscillatorNShadow, lv_color_hex(0xE55E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_oscillatorNShadow, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_oscillatorNShadow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_oscillatorNShadow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_oscillatorNShadow, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_oscillatorNShadow, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_oscillatorNShadow, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_oscillatorN = lv_label_create(ui_DCON);
    lv_obj_set_width(ui_oscillatorN, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_oscillatorN, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_oscillatorN, LV_ALIGN_CENTER);
    lv_label_set_text(ui_oscillatorN, "208");
    lv_obj_set_style_text_color(ui_oscillatorN, lv_color_hex(0xE55E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_oscillatorN, 230, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_oscillatorN, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_oscillatorN, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_oscillatorN, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_oscillatorN, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_oscillatorN, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OFFSETTITLE = lv_obj_create(ui_manualCalibrationPanel);
    lv_obj_remove_style_all(ui_OFFSETTITLE);
    lv_obj_set_width(ui_OFFSETTITLE, 128);
    lv_obj_set_height(ui_OFFSETTITLE, 22);
    lv_obj_set_x(ui_OFFSETTITLE, -65);
    lv_obj_set_y(ui_OFFSETTITLE, -27);
    lv_obj_set_align(ui_OFFSETTITLE, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_OFFSETTITLE, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_offsetTitleShadow = lv_label_create(ui_OFFSETTITLE);
    lv_obj_set_width(ui_offsetTitleShadow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_offsetTitleShadow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_offsetTitleShadow, -3);
    lv_obj_set_y(ui_offsetTitleShadow, -2);
    lv_label_set_text(ui_offsetTitleShadow, "OFFSET:");
    lv_obj_set_style_text_color(ui_offsetTitleShadow, lv_color_hex(0xE55E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_offsetTitleShadow, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_offsetTitleShadow, &ui_font_Square22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_offsetTitleShadow, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_offsetTitle = lv_label_create(ui_OFFSETTITLE);
    lv_obj_set_width(ui_offsetTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_offsetTitle, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_offsetTitle, "OFFSET:");
    lv_obj_set_style_text_color(ui_offsetTitle, lv_color_hex(0xE55E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_offsetTitle, 240, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_offsetTitle, &ui_font_Square22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_offsetTitle, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OFFSET = lv_obj_create(ui_manualCalibrationPanel);
    lv_obj_remove_style_all(ui_OFFSET);
    lv_obj_set_width(ui_OFFSET, 100);
    lv_obj_set_height(ui_OFFSET, 50);
    lv_obj_set_x(ui_OFFSET, 19);
    lv_obj_set_y(ui_OFFSET, -29);
    lv_obj_set_align(ui_OFFSET, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_OFFSET, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_calibrationOffsetShadow = lv_label_create(ui_OFFSET);
    lv_obj_set_width(ui_calibrationOffsetShadow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_calibrationOffsetShadow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_calibrationOffsetShadow, -4);
    lv_obj_set_y(ui_calibrationOffsetShadow, -1);
    lv_obj_set_align(ui_calibrationOffsetShadow, LV_ALIGN_CENTER);
    lv_label_set_text(ui_calibrationOffsetShadow, "208");
    lv_obj_set_style_text_color(ui_calibrationOffsetShadow, lv_color_hex(0xE55E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_calibrationOffsetShadow, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_calibrationOffsetShadow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_calibrationOffsetShadow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_calibrationOffsetShadow, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_calibrationOffsetShadow, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_calibrationOffsetShadow, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_calibrationOffset = lv_label_create(ui_OFFSET);
    lv_obj_set_width(ui_calibrationOffset, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_calibrationOffset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_calibrationOffset, LV_ALIGN_CENTER);
    lv_label_set_text(ui_calibrationOffset, "208");
    lv_obj_set_style_text_color(ui_calibrationOffset, lv_color_hex(0xE55E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_calibrationOffset, 230, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_calibrationOffset, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_calibrationOffset, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_calibrationOffset, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_calibrationOffset, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_calibrationOffset, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GAPTITLE = lv_obj_create(ui_manualCalibrationPanel);
    lv_obj_remove_style_all(ui_GAPTITLE);
    lv_obj_set_width(ui_GAPTITLE, 128);
    lv_obj_set_height(ui_GAPTITLE, 22);
    lv_obj_set_x(ui_GAPTITLE, -65);
    lv_obj_set_y(ui_GAPTITLE, 28);
    lv_obj_set_align(ui_GAPTITLE, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_GAPTITLE, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_gapTitleShadow = lv_label_create(ui_GAPTITLE);
    lv_obj_set_width(ui_gapTitleShadow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gapTitleShadow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gapTitleShadow, -3);
    lv_obj_set_y(ui_gapTitleShadow, -2);
    lv_label_set_text(ui_gapTitleShadow, "GAP:");
    lv_obj_set_style_text_color(ui_gapTitleShadow, lv_color_hex(0xE55E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gapTitleShadow, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gapTitleShadow, &ui_font_Square22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_gapTitleShadow, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gapTitle = lv_label_create(ui_GAPTITLE);
    lv_obj_set_width(ui_gapTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gapTitle, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_gapTitle, "GAP:");
    lv_obj_set_style_text_color(ui_gapTitle, lv_color_hex(0xE55E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gapTitle, 240, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gapTitle, &ui_font_Square22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_gapTitle, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GAP = lv_obj_create(ui_manualCalibrationPanel);
    lv_obj_remove_style_all(ui_GAP);
    lv_obj_set_width(ui_GAP, 133);
    lv_obj_set_height(ui_GAP, 50);
    lv_obj_set_x(ui_GAP, -14);
    lv_obj_set_y(ui_GAP, 25);
    lv_obj_set_align(ui_GAP, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_GAP, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_calibrationGapShadow = lv_label_create(ui_GAP);
    lv_obj_set_width(ui_calibrationGapShadow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_calibrationGapShadow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_calibrationGapShadow, -4);
    lv_obj_set_y(ui_calibrationGapShadow, -1);
    lv_obj_set_align(ui_calibrationGapShadow, LV_ALIGN_CENTER);
    lv_label_set_text(ui_calibrationGapShadow, "208");
    lv_obj_set_style_text_color(ui_calibrationGapShadow, lv_color_hex(0xE55E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_calibrationGapShadow, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_calibrationGapShadow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_calibrationGapShadow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_calibrationGapShadow, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_calibrationGapShadow, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_calibrationGapShadow, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_calibrationGap = lv_label_create(ui_GAP);
    lv_obj_set_width(ui_calibrationGap, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_calibrationGap, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_calibrationGap, LV_ALIGN_CENTER);
    lv_label_set_text(ui_calibrationGap, "208");
    lv_obj_set_style_text_color(ui_calibrationGap, lv_color_hex(0xE55E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_calibrationGap, 230, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_calibrationGap, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_calibrationGap, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_calibrationGap, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_calibrationGap, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_calibrationGap, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WAVEFORMTITLE = lv_obj_create(ui_manualCalibrationPanel);
    lv_obj_remove_style_all(ui_WAVEFORMTITLE);
    lv_obj_set_width(ui_WAVEFORMTITLE, 131);
    lv_obj_set_height(ui_WAVEFORMTITLE, 22);
    lv_obj_set_x(ui_WAVEFORMTITLE, -71);
    lv_obj_set_y(ui_WAVEFORMTITLE, 83);
    lv_obj_set_align(ui_WAVEFORMTITLE, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_WAVEFORMTITLE, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_waveformTitleShadow = lv_label_create(ui_WAVEFORMTITLE);
    lv_obj_set_width(ui_waveformTitleShadow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_waveformTitleShadow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_waveformTitleShadow, -3);
    lv_obj_set_y(ui_waveformTitleShadow, -2);
    lv_obj_set_align(ui_waveformTitleShadow, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_waveformTitleShadow, "WAVEFORM:");
    lv_obj_set_style_text_color(ui_waveformTitleShadow, lv_color_hex(0xE55E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_waveformTitleShadow, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_waveformTitleShadow, &ui_font_Square22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_waveformTitleShadow, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_waveformTitle = lv_label_create(ui_WAVEFORMTITLE);
    lv_obj_set_width(ui_waveformTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_waveformTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_waveformTitle, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_waveformTitle, "WAVEFORM:");
    lv_obj_set_style_text_color(ui_waveformTitle, lv_color_hex(0xE55E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_waveformTitle, 240, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_waveformTitle, &ui_font_Square22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_waveformTitle, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WAVEFORM = lv_obj_create(ui_manualCalibrationPanel);
    lv_obj_remove_style_all(ui_WAVEFORM);
    lv_obj_set_width(ui_WAVEFORM, 121);
    lv_obj_set_height(ui_WAVEFORM, 50);
    lv_obj_set_x(ui_WAVEFORM, 62);
    lv_obj_set_y(ui_WAVEFORM, 77);
    lv_obj_set_align(ui_WAVEFORM, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_WAVEFORM, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_waveformShadow = lv_label_create(ui_WAVEFORM);
    lv_obj_set_width(ui_waveformShadow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_waveformShadow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_waveformShadow, -4);
    lv_obj_set_y(ui_waveformShadow, -1);
    lv_obj_set_align(ui_waveformShadow, LV_ALIGN_CENTER);
    lv_label_set_text(ui_waveformShadow, "SAW");
    lv_obj_set_style_text_color(ui_waveformShadow, lv_color_hex(0xE55E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_waveformShadow, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_waveformShadow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_waveformShadow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_waveformShadow, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_waveformShadow, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_waveformShadow, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_waveform = lv_label_create(ui_WAVEFORM);
    lv_obj_set_width(ui_waveform, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_waveform, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_waveform, LV_ALIGN_CENTER);
    lv_label_set_text(ui_waveform, "SAW");
    lv_obj_set_style_text_color(ui_waveform, lv_color_hex(0xE55E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_waveform, 230, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_waveform, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_waveform, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_waveform, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_waveform, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_waveform, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_calibrationCompleteMessage = lv_textarea_create(ui_MANUALCALIBRATION);
    lv_obj_set_width(ui_calibrationCompleteMessage, 253);
    lv_obj_set_height(ui_calibrationCompleteMessage, 73);
    lv_obj_set_x(ui_calibrationCompleteMessage, 5);
    lv_obj_set_y(ui_calibrationCompleteMessage, -3);
    lv_obj_set_align(ui_calibrationCompleteMessage, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_calibrationCompleteMessage, "CALIBRATION COMPLETE");
    lv_obj_add_flag(ui_calibrationCompleteMessage, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_calibrationCompleteMessage, lv_color_hex(0xFFB131), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_calibrationCompleteMessage, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_calibrationCompleteMessage, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_calibrationCompleteMessage, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_calibrationCompleteMessage, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_calibrationCompleteMessage, lv_color_hex(0xF51419), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_calibrationCompleteMessage, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_calibrationCompleteMessage, LV_GRAD_DIR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_calibrationCompleteMessage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_calibrationCompleteMessage, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_calibrationCompleteMessage, lv_color_hex(0xFF0C00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_calibrationCompleteMessage, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_calibrationCompleteMessage, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_calibrationCompleteMessage, 30, LV_PART_MAIN | LV_STATE_DEFAULT);



}
