// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: DCO_v4

#include "ui.h"

void ui_Main1_screen_init(void)
{
    ui_Main1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Main1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Main1, lv_color_hex(0x566876), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main1, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Main1, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BACKGRCONTRAST);
    ui_object_set_themeable_style_property(ui_Main1, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BACKGRCONTRAST);

    ui_PresetNamePanel1 = lv_obj_create(ui_Main1);
    lv_obj_set_width(ui_PresetNamePanel1, 320);
    lv_obj_set_height(ui_PresetNamePanel1, 29);
    lv_obj_set_x(ui_PresetNamePanel1, 0);
    lv_obj_set_y(ui_PresetNamePanel1, -58);
    lv_obj_set_align(ui_PresetNamePanel1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PresetNamePanel1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_PresetNamePanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PresetNamePanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PresetNamePanel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PresetNamePanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PresetNamePanel1, lv_color_hex(0xAC7939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PresetNamePanel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PresetNamePanel1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetSavePanel1 = lv_obj_create(ui_Main1);
    lv_obj_set_width(ui_PresetSavePanel1, 296);
    lv_obj_set_height(ui_PresetSavePanel1, 216);
    lv_obj_set_x(ui_PresetSavePanel1, 0);
    lv_obj_set_y(ui_PresetSavePanel1, -1);
    lv_obj_set_align(ui_PresetSavePanel1, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_PresetSavePanel1, LV_STATE_USER_1);       /// States
    lv_obj_add_flag(ui_PresetSavePanel1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_PresetSavePanel1,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_PresetSavePanel1, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_PresetSavePanel1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PresetSavePanel1, lv_color_hex(0x831918), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PresetSavePanel1, 220, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PresetSavePanel1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PresetSavePanel1, lv_color_hex(0x810202), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_PresetSavePanel1, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_PresetSavePanel1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_PresetSavePanel1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PresetSavePanel1, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetSaveFromTitleShadow1 = lv_label_create(ui_PresetSavePanel1);
    lv_obj_set_width(ui_PresetSaveFromTitleShadow1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PresetSaveFromTitleShadow1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PresetSaveFromTitleShadow1, -6);
    lv_obj_set_y(ui_PresetSaveFromTitleShadow1, -10);
    lv_label_set_text(ui_PresetSaveFromTitleShadow1, "Saving FROM:");
    lv_obj_set_style_text_color(ui_PresetSaveFromTitleShadow1, lv_color_hex(0xE55E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetSaveFromTitleShadow1, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetSaveFromTitleShadow1, &ui_font_Square22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PresetSaveFromTitleShadow1, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetSaveFromTitle1 = lv_label_create(ui_PresetSavePanel1);
    lv_obj_set_width(ui_PresetSaveFromTitle1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PresetSaveFromTitle1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PresetSaveFromTitle1, -4);
    lv_obj_set_y(ui_PresetSaveFromTitle1, -7);
    lv_label_set_text(ui_PresetSaveFromTitle1, "Saving FROM:");
    lv_obj_set_style_text_color(ui_PresetSaveFromTitle1, lv_color_hex(0xE55E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetSaveFromTitle1, 240, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetSaveFromTitle1, &ui_font_Square22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PresetSaveFromTitle1, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetNOLDShadow1 = lv_label_create(ui_PresetSavePanel1);
    lv_obj_set_width(ui_PresetNOLDShadow1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PresetNOLDShadow1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PresetNOLDShadow1, 70);
    lv_obj_set_y(ui_PresetNOLDShadow1, -85);
    lv_obj_set_align(ui_PresetNOLDShadow1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PresetNOLDShadow1, "208");
    lv_obj_set_style_text_color(ui_PresetNOLDShadow1, lv_color_hex(0xE55E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetNOLDShadow1, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_PresetNOLDShadow1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_PresetNOLDShadow1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PresetNOLDShadow1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetNOLDShadow1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PresetNOLDShadow1, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetNOLD1 = lv_label_create(ui_PresetSavePanel1);
    lv_obj_set_width(ui_PresetNOLD1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PresetNOLD1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PresetNOLD1, 74);
    lv_obj_set_y(ui_PresetNOLD1, -84);
    lv_obj_set_align(ui_PresetNOLD1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PresetNOLD1, "208");
    lv_obj_set_style_text_color(ui_PresetNOLD1, lv_color_hex(0xE55E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetNOLD1, 230, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_PresetNOLD1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_PresetNOLD1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PresetNOLD1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetNOLD1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PresetNOLD1, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetNameOLDShadow1 = lv_label_create(ui_PresetSavePanel1);
    lv_obj_set_width(ui_PresetNameOLDShadow1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PresetNameOLDShadow1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PresetNameOLDShadow1, 37);
    lv_obj_set_y(ui_PresetNameOLDShadow1, 35);
    lv_label_set_text(ui_PresetNameOLDShadow1, "PRESET NAME");
    lv_obj_set_style_text_color(ui_PresetNameOLDShadow1, lv_color_hex(0xE55E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetNameOLDShadow1, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetNameOLDShadow1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PresetNameOLDShadow1, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetNameOLD1 = lv_label_create(ui_PresetSavePanel1);
    lv_obj_set_width(ui_PresetNameOLD1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PresetNameOLD1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PresetNameOLD1, 40);
    lv_obj_set_y(ui_PresetNameOLD1, 37);
    lv_label_set_text(ui_PresetNameOLD1, "PRESET NAME");
    lv_obj_set_style_text_color(ui_PresetNameOLD1, lv_color_hex(0xE55E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetNameOLD1, 240, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetNameOLD1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PresetNameOLD1, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetSaveToShadow1 = lv_label_create(ui_PresetSavePanel1);
    lv_obj_set_width(ui_PresetSaveToShadow1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PresetSaveToShadow1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PresetSaveToShadow1, -10);
    lv_obj_set_y(ui_PresetSaveToShadow1, 76);
    lv_label_set_text(ui_PresetSaveToShadow1, "TO:");
    lv_obj_set_style_text_color(ui_PresetSaveToShadow1, lv_color_hex(0xE55E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetSaveToShadow1, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetSaveToShadow1, &ui_font_Square22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PresetSaveToShadow1, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetSaveTo1 = lv_label_create(ui_PresetSavePanel1);
    lv_obj_set_width(ui_PresetSaveTo1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PresetSaveTo1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PresetSaveTo1, -6);
    lv_obj_set_y(ui_PresetSaveTo1, 79);
    lv_label_set_text(ui_PresetSaveTo1, "TO:");
    lv_obj_set_style_text_color(ui_PresetSaveTo1, lv_color_hex(0xE55E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetSaveTo1, 240, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetSaveTo1, &ui_font_Square22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PresetSaveTo1, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetNNewShadow1 = lv_label_create(ui_PresetSavePanel1);
    lv_obj_set_width(ui_PresetNNewShadow1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PresetNNewShadow1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PresetNNewShadow1, 68);
    lv_obj_set_y(ui_PresetNNewShadow1, 17);
    lv_obj_set_align(ui_PresetNNewShadow1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PresetNNewShadow1, "208");
    lv_obj_set_style_text_color(ui_PresetNNewShadow1, lv_color_hex(0xE55E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetNNewShadow1, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_PresetNNewShadow1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_PresetNNewShadow1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PresetNNewShadow1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetNNewShadow1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PresetNNewShadow1, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetNNew1 = lv_label_create(ui_PresetSavePanel1);
    lv_obj_set_width(ui_PresetNNew1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PresetNNew1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PresetNNew1, 72);
    lv_obj_set_y(ui_PresetNNew1, 18);
    lv_obj_set_align(ui_PresetNNew1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PresetNNew1, "208");
    lv_obj_set_style_text_color(ui_PresetNNew1, lv_color_hex(0xE55E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetNNew1, 230, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_PresetNNew1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_PresetNNew1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PresetNNew1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetNNew1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PresetNNew1, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetNameNew1 = lv_label_create(ui_PresetSavePanel1);
    lv_obj_set_width(ui_PresetNameNew1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PresetNameNew1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PresetNameNew1, 40);
    lv_obj_set_y(ui_PresetNameNew1, 145);
    lv_label_set_text(ui_PresetNameNew1, "PRESET NAME");
    lv_obj_set_style_text_color(ui_PresetNameNew1, lv_color_hex(0xE55E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetNameNew1, 240, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetNameNew1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PresetNameNew1, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetNameNewShadow1 = lv_label_create(ui_PresetSavePanel1);
    lv_obj_set_width(ui_PresetNameNewShadow1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PresetNameNewShadow1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PresetNameNewShadow1, 37);
    lv_obj_set_y(ui_PresetNameNewShadow1, 142);
    lv_label_set_text(ui_PresetNameNewShadow1, "PRESET NAME");
    lv_obj_set_style_text_color(ui_PresetNameNewShadow1, lv_color_hex(0xE55E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetNameNewShadow1, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetNameNewShadow1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PresetNameNewShadow1, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetNewName1 = lv_textarea_create(ui_Main1);
    lv_obj_set_width(ui_PresetNewName1, 255);
    lv_obj_set_height(ui_PresetNewName1, LV_SIZE_CONTENT);    /// 51
    lv_obj_set_x(ui_PresetNewName1, 4);
    lv_obj_set_y(ui_PresetNewName1, 54);
    lv_obj_set_align(ui_PresetNewName1, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_PresetNewName1, 12);
    lv_textarea_set_one_line(ui_PresetNewName1, true);
    lv_obj_add_state(ui_PresetNewName1, LV_STATE_FOCUSED);       /// States
    lv_obj_add_flag(ui_PresetNewName1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_WITH_ARROW);     /// Flags
    lv_obj_remove_flag(ui_PresetNewName1,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_PresetNewName1, lv_color_hex(0x8C0E0E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetNewName1, 240, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PresetNewName1, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetNewName1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PresetNewName1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PresetNewName1, lv_color_hex(0xF51419), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PresetNewName1, 210, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_PresetNewName1, lv_color_hex(0xFFAF2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PresetNewName1, lv_color_hex(0x050000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PresetNewName1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PresetNewName1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PresetNewName1, lv_color_hex(0xFF0C00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_PresetNewName1, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_PresetNewName1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_PresetNewName1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_PresetNewName1, lv_color_hex(0x1D0101), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetNewName1, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PresetNewName1, lv_color_hex(0xE50B00), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PresetNewName1, 160, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PresetNewName1, LV_BLEND_MODE_ADDITIVE, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_PresetNewName1, lv_color_hex(0xFF1A15), LV_PART_CURSOR | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_PresetNewName1, 220, LV_PART_CURSOR | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_PresetNewName1, lv_color_hex(0x7C1515), LV_PART_CURSOR | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_PresetNewName1, 255, LV_PART_CURSOR | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_PresetNewName1, lv_color_hex(0xFF0000), LV_PART_CURSOR | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_PresetNewName1, 150, LV_PART_CURSOR | LV_STATE_FOCUSED);

    ui_PresetSavedMesage1 = lv_textarea_create(ui_Main1);
    lv_obj_set_width(ui_PresetSavedMesage1, 253);
    lv_obj_set_height(ui_PresetSavedMesage1, 51);
    lv_obj_set_x(ui_PresetSavedMesage1, 3);
    lv_obj_set_y(ui_PresetSavedMesage1, 12);
    lv_obj_set_align(ui_PresetSavedMesage1, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_PresetSavedMesage1, "PRESET SAVED");
    lv_obj_add_flag(ui_PresetSavedMesage1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_PresetSavedMesage1, lv_color_hex(0xFFB131), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetSavedMesage1, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PresetSavedMesage1, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetSavedMesage1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PresetSavedMesage1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PresetSavedMesage1, lv_color_hex(0xF51419), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PresetSavedMesage1, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_PresetSavedMesage1, LV_GRAD_DIR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PresetSavedMesage1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PresetSavedMesage1, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PresetSavedMesage1, lv_color_hex(0xFF0C00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_PresetSavedMesage1, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_PresetSavedMesage1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_PresetSavedMesage1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_TabView1 = lv_tabview_create(ui_Main1);
    lv_tabview_set_tab_bar_size(ui_TabView1, 20);
    lv_obj_set_width(ui_TabView1, 320);
    lv_obj_set_height(ui_TabView1, 240);
    lv_obj_set_align(ui_TabView1, LV_ALIGN_TOP_MID);
    lv_obj_add_state(ui_TabView1, LV_STATE_CHECKED | LV_STATE_PRESSED | LV_STATE_FOCUSED | LV_STATE_DISABLED |
                     LV_STATE_EDITED);      /// States
    lv_obj_add_flag(ui_TabView1, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_remove_flag(ui_TabView1, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE |
                       LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_TabView1, lv_color_hex(0x566876), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabView1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_TabView1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TabView1, lv_color_hex(0xE1913B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TabView1, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TabView1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_TabView1, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_TabView1, lv_color_hex(0xFF3B18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_TabView1, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_TabView1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_TabView1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_TabView1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_TabView1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_TabView1, lv_color_hex(0xE1913B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TabView1, 240, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TabView1, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TabView1, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_TabView1, lv_color_hex(0xFF3B18), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_TabView1, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_TabView1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_TabView1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_TabView1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_bg_opa(ui_TabView1, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_text_color(ui_TabView1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_TabView1, 255, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_TabView1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_text_opa(ui_TabView1, 255, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_FOCUS_KEY);

    lv_obj_set_style_border_color(lv_tabview_get_tab_bar(ui_TabView1), lv_color_hex(0xFF3B18),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(lv_tabview_get_tab_bar(ui_TabView1), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(lv_tabview_get_tab_bar(ui_TabView1), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(lv_tabview_get_tab_bar(ui_TabView1), lv_color_hex(0xFF3B18),
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(lv_tabview_get_tab_bar(ui_TabView1), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(lv_tabview_get_tab_bar(ui_TabView1), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(lv_tabview_get_tab_bar(ui_TabView1), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_bar(ui_TabView1),  LV_PART_MAIN | LV_STATE_CHECKED,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_TEXTCONTRAST);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_bar(ui_TabView1),  LV_PART_MAIN | LV_STATE_CHECKED,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_TEXTCONTRAST);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_bar(ui_TabView1),  LV_PART_MAIN | LV_STATE_CHECKED,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_BACKGRCONTRAST);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_bar(ui_TabView1),  LV_PART_MAIN | LV_STATE_CHECKED,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_BACKGRCONTRAST);
    lv_obj_set_style_text_color(lv_tabview_get_tab_bar(ui_TabView1), lv_color_hex(0x808080),
                                LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(lv_tabview_get_tab_bar(ui_TabView1), 255,  LV_PART_MAIN | LV_STATE_PRESSED);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_bar(ui_TabView1),  LV_PART_MAIN | LV_STATE_PRESSED,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_BACKGRCONTRAST);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_bar(ui_TabView1),  LV_PART_MAIN | LV_STATE_PRESSED,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_BACKGRCONTRAST);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_bar(ui_TabView1),  LV_PART_MAIN | LV_STATE_DISABLED,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_BACKGRCONTRAST);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_bar(ui_TabView1),  LV_PART_MAIN | LV_STATE_DISABLED,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_BACKGRCONTRAST);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_bar(ui_TabView1),  LV_PART_MAIN | LV_STATE_EDITED,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_BACKGRCONTRAST);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_bar(ui_TabView1),  LV_PART_MAIN | LV_STATE_EDITED,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_BACKGRCONTRAST);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_bar(ui_TabView1),  LV_PART_MAIN | LV_STATE_SCROLLED,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_BACKGRCONTRAST);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_bar(ui_TabView1),  LV_PART_MAIN | LV_STATE_SCROLLED,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_BACKGRCONTRAST);
    lv_obj_set_style_text_color(lv_tabview_get_tab_bar(ui_TabView1), lv_color_hex(0x808080),
                                LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(lv_tabview_get_tab_bar(ui_TabView1), 255,  LV_PART_MAIN | LV_STATE_FOCUSED);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_bar(ui_TabView1),  LV_PART_MAIN | LV_STATE_FOCUSED,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_BACKGRCONTRAST);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_bar(ui_TabView1),  LV_PART_MAIN | LV_STATE_FOCUSED,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_BACKGRCONTRAST);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_bar(ui_TabView1),  LV_PART_MAIN | LV_STATE_FOCUS_KEY,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_BACKGRCONTRAST);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_bar(ui_TabView1),  LV_PART_MAIN | LV_STATE_FOCUS_KEY,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_BACKGRCONTRAST);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_bar(ui_TabView1),
                                           LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_FOCUSED, LV_STYLE_BG_COLOR, _ui_theme_color_BACKGRCONTRAST);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_bar(ui_TabView1),
                                           LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_FOCUSED, LV_STYLE_BG_OPA, _ui_theme_alpha_BACKGRCONTRAST);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_bar(ui_TabView1),
                                           LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED, LV_STYLE_BG_COLOR, _ui_theme_color_BACKGRCONTRAST);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_bar(ui_TabView1),
                                           LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED, LV_STYLE_BG_OPA, _ui_theme_alpha_BACKGRCONTRAST);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_bar(ui_TabView1),
                                           LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_FOCUS_KEY, LV_STYLE_BG_COLOR, _ui_theme_color_BACKGRCONTRAST);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_bar(ui_TabView1),
                                           LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_FOCUS_KEY, LV_STYLE_BG_OPA, _ui_theme_alpha_BACKGRCONTRAST);

    lv_obj_set_style_border_color(lv_tabview_get_tab_bar(ui_TabView1), lv_color_hex(0xFF3B18),
                                  LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(lv_tabview_get_tab_bar(ui_TabView1), 255,  LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(lv_tabview_get_tab_bar(ui_TabView1), lv_color_hex(0xFF3B18),
                                   LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(lv_tabview_get_tab_bar(ui_TabView1), 255,  LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(lv_tabview_get_tab_bar(ui_TabView1), 0,  LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(lv_tabview_get_tab_bar(ui_TabView1), 0,  LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(lv_tabview_get_tab_bar(ui_TabView1), lv_color_hex(0xFF3B18),
                                LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(lv_tabview_get_tab_bar(ui_TabView1), 255,  LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(lv_tabview_get_tab_bar(ui_TabView1), lv_color_hex(0xFFFFFF),
                                LV_PART_ITEMS | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(lv_tabview_get_tab_bar(ui_TabView1), 255,  LV_PART_ITEMS | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(lv_tabview_get_tab_bar(ui_TabView1), lv_color_hex(0xFFFFFF),
                              LV_PART_ITEMS | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_bar(ui_TabView1), 255,  LV_PART_ITEMS | LV_STATE_PRESSED);
    lv_obj_set_style_text_color(lv_tabview_get_tab_bar(ui_TabView1), lv_color_hex(0x808080),
                                LV_PART_ITEMS | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(lv_tabview_get_tab_bar(ui_TabView1), 255,  LV_PART_ITEMS | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(lv_tabview_get_tab_bar(ui_TabView1), lv_color_hex(0x808080),
                                LV_PART_ITEMS | LV_STATE_CHECKED | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(lv_tabview_get_tab_bar(ui_TabView1), 255,
                              LV_PART_ITEMS | LV_STATE_CHECKED | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(lv_tabview_get_tab_bar(ui_TabView1), lv_color_hex(0x808080),
                                LV_PART_ITEMS | LV_STATE_CHECKED | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_text_opa(lv_tabview_get_tab_bar(ui_TabView1), 255,
                              LV_PART_ITEMS | LV_STATE_CHECKED | LV_STATE_FOCUS_KEY);

    ui_DCOTab = lv_tabview_add_tab(ui_TabView1, "DCO");
    lv_obj_add_state(ui_DCOTab, LV_STATE_FOCUSED);       /// States
    lv_obj_set_style_border_color(ui_DCOTab, lv_color_hex(0xFF3B18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_DCOTab, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DCOTab, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_DCOTab, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DCOTab, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_SCROLLED);
    lv_obj_set_style_bg_opa(ui_DCOTab, 255, LV_PART_MAIN | LV_STATE_SCROLLED);

    lv_obj_set_style_bg_color(ui_DCOTab, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_SCROLLED);
    lv_obj_set_style_bg_opa(ui_DCOTab, 255, LV_PART_SCROLLBAR | LV_STATE_SCROLLED);

    ui_TopBarPanel1 = lv_obj_create(ui_DCOTab);
    lv_obj_set_width(ui_TopBarPanel1, 316);
    lv_obj_set_height(ui_TopBarPanel1, 50);
    lv_obj_set_x(ui_TopBarPanel1, -1);
    lv_obj_set_y(ui_TopBarPanel1, -9);
    lv_obj_set_align(ui_TopBarPanel1, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_TopBarPanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TopBarPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TopBarPanel1, lv_color_hex(0x181008), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TopBarPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TopBarPanel1, lv_color_hex(0xB47D41), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TopBarPanel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TopBarPanel1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OSC1Level1 = ui_BAR2_create(ui_TopBarPanel1);
    lv_obj_set_x(ui_OSC1Level1, 0);
    lv_obj_set_y(ui_OSC1Level1, -15);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    ui_OSC2Level1 = ui_BAR2_create(ui_TopBarPanel1);
    lv_obj_set_x(ui_OSC2Level1, 0);
    lv_obj_set_y(ui_OSC2Level1, 0);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    ui_SUBLevel1 = ui_BAR2_create(ui_TopBarPanel1);
    lv_obj_set_x(ui_SUBLevel1, 0);
    lv_obj_set_y(ui_SUBLevel1, 15);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    ui_ENVTab = lv_tabview_add_tab(ui_TabView1, "ENV");

    ui_Label4 = lv_label_create(ui_ENVTab);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -45);
    lv_obj_set_y(ui_Label4, -71);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, " VCF restart attack");
    ui_object_set_themeable_style_property(ui_Label4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TEXTSHADOW);
    ui_object_set_themeable_style_property(ui_Label4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TEXTSHADOW);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Label4);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -1);
    lv_obj_set_y(ui_Label3, 1);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, " VCF restart attack");
    ui_object_set_themeable_style_property(ui_Label3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TEXT);
    ui_object_set_themeable_style_property(ui_Label3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TEXT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_ENVTab);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -46);
    lv_obj_set_y(ui_Label2, -91);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, " VCA restart attack");
    ui_object_set_themeable_style_property(ui_Label2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TEXTSHADOW);
    ui_object_set_themeable_style_property(ui_Label2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TEXTSHADOW);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Label2);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -1);
    lv_obj_set_y(ui_Label1, 1);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, " VCA restart attack");
    ui_object_set_themeable_style_property(ui_Label1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TEXT);
    ui_object_set_themeable_style_property(ui_Label1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TEXT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch2 = lv_switch_create(ui_ENVTab);
    lv_obj_set_width(ui_Switch2, 30);
    lv_obj_set_height(ui_Switch2, 17);
    lv_obj_set_x(ui_Switch2, -133);
    lv_obj_set_y(ui_Switch2, -91);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switch2, lv_color_hex(0x831918), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch2, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Switch2, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Switch2, lv_color_hex(0x690707), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch2, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_color(ui_Switch2, lv_color_hex(0xFF9400), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_main_stop(ui_Switch2, 100, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_stop(ui_Switch2, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_dir(ui_Switch2, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_blend_mode(ui_Switch2, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_Switch2, lv_color_hex(0x92EEFF), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_Switch2, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_object_set_themeable_style_property(ui_Switch2, LV_PART_INDICATOR | LV_STATE_CHECKED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_TEXTSHADOW);
    ui_object_set_themeable_style_property(ui_Switch2, LV_PART_INDICATOR | LV_STATE_CHECKED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_TEXTSHADOW);
    ui_object_set_themeable_style_property(ui_Switch2, LV_PART_INDICATOR | LV_STATE_CHECKED, LV_STYLE_BG_GRAD_COLOR,
                                           _ui_theme_color_TEXT);
    lv_obj_set_style_bg_main_stop(ui_Switch2, 10, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_stop(ui_Switch2, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_dir(ui_Switch2, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_object_set_themeable_style_property(ui_Switch2, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_TEXTSHADOW);
    ui_object_set_themeable_style_property(ui_Switch2, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_TEXTSHADOW);
    lv_obj_set_style_bg_color(ui_Switch2, lv_color_hex(0xEBC4B0), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch2, 220, LV_PART_KNOB | LV_STATE_CHECKED);

    ui_Switch3 = lv_switch_create(ui_ENVTab);
    lv_obj_set_width(ui_Switch3, 30);
    lv_obj_set_height(ui_Switch3, 17);
    lv_obj_set_x(ui_Switch3, -133);
    lv_obj_set_y(ui_Switch3, -11);
    lv_obj_set_align(ui_Switch3, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switch3, lv_color_hex(0x831918), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch3, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Switch3, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Switch3, lv_color_hex(0x690707), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch3, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_color(ui_Switch3, lv_color_hex(0xFF9400), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_main_stop(ui_Switch3, 100, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_stop(ui_Switch3, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_dir(ui_Switch3, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_blend_mode(ui_Switch3, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_Switch3, lv_color_hex(0x92EEFF), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_Switch3, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_object_set_themeable_style_property(ui_Switch3, LV_PART_INDICATOR | LV_STATE_CHECKED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_TEXTSHADOW);
    ui_object_set_themeable_style_property(ui_Switch3, LV_PART_INDICATOR | LV_STATE_CHECKED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_TEXTSHADOW);
    ui_object_set_themeable_style_property(ui_Switch3, LV_PART_INDICATOR | LV_STATE_CHECKED, LV_STYLE_BG_GRAD_COLOR,
                                           _ui_theme_color_TEXT);
    lv_obj_set_style_bg_main_stop(ui_Switch3, 10, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_stop(ui_Switch3, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_dir(ui_Switch3, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_object_set_themeable_style_property(ui_Switch3, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_TEXTSHADOW);
    ui_object_set_themeable_style_property(ui_Switch3, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_TEXTSHADOW);
    lv_obj_set_style_bg_color(ui_Switch3, lv_color_hex(0xEBC4B0), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch3, 220, LV_PART_KNOB | LV_STATE_CHECKED);

    ui_Switch4 = lv_switch_create(ui_ENVTab);
    lv_obj_set_width(ui_Switch4, 30);
    lv_obj_set_height(ui_Switch4, 17);
    lv_obj_set_x(ui_Switch4, -133);
    lv_obj_set_y(ui_Switch4, -31);
    lv_obj_set_align(ui_Switch4, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switch4, lv_color_hex(0x831918), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch4, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Switch4, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Switch4, lv_color_hex(0x690707), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch4, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_color(ui_Switch4, lv_color_hex(0xFF9400), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_main_stop(ui_Switch4, 100, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_stop(ui_Switch4, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_dir(ui_Switch4, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_blend_mode(ui_Switch4, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_Switch4, lv_color_hex(0x92EEFF), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_Switch4, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_object_set_themeable_style_property(ui_Switch4, LV_PART_INDICATOR | LV_STATE_CHECKED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_TEXTSHADOW);
    ui_object_set_themeable_style_property(ui_Switch4, LV_PART_INDICATOR | LV_STATE_CHECKED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_TEXTSHADOW);
    ui_object_set_themeable_style_property(ui_Switch4, LV_PART_INDICATOR | LV_STATE_CHECKED, LV_STYLE_BG_GRAD_COLOR,
                                           _ui_theme_color_TEXT);
    lv_obj_set_style_bg_main_stop(ui_Switch4, 10, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_stop(ui_Switch4, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_dir(ui_Switch4, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_object_set_themeable_style_property(ui_Switch4, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_TEXTSHADOW);
    ui_object_set_themeable_style_property(ui_Switch4, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_TEXTSHADOW);
    lv_obj_set_style_bg_color(ui_Switch4, lv_color_hex(0xEBC4B0), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch4, 220, LV_PART_KNOB | LV_STATE_CHECKED);

    ui_Switch5 = lv_switch_create(ui_ENVTab);
    lv_obj_set_width(ui_Switch5, 30);
    lv_obj_set_height(ui_Switch5, 17);
    lv_obj_set_x(ui_Switch5, -133);
    lv_obj_set_y(ui_Switch5, -51);
    lv_obj_set_align(ui_Switch5, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switch5, lv_color_hex(0x831918), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch5, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Switch5, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Switch5, lv_color_hex(0x690707), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch5, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_color(ui_Switch5, lv_color_hex(0xFF9400), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_main_stop(ui_Switch5, 100, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_stop(ui_Switch5, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_dir(ui_Switch5, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_blend_mode(ui_Switch5, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_Switch5, lv_color_hex(0x92EEFF), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_Switch5, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_object_set_themeable_style_property(ui_Switch5, LV_PART_INDICATOR | LV_STATE_CHECKED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_TEXTSHADOW);
    ui_object_set_themeable_style_property(ui_Switch5, LV_PART_INDICATOR | LV_STATE_CHECKED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_TEXTSHADOW);
    ui_object_set_themeable_style_property(ui_Switch5, LV_PART_INDICATOR | LV_STATE_CHECKED, LV_STYLE_BG_GRAD_COLOR,
                                           _ui_theme_color_TEXT);
    lv_obj_set_style_bg_main_stop(ui_Switch5, 10, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_stop(ui_Switch5, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_dir(ui_Switch5, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_object_set_themeable_style_property(ui_Switch5, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_TEXTSHADOW);
    ui_object_set_themeable_style_property(ui_Switch5, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_TEXTSHADOW);
    lv_obj_set_style_bg_color(ui_Switch5, lv_color_hex(0xEBC4B0), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch5, 220, LV_PART_KNOB | LV_STATE_CHECKED);

    ui_Switch6 = lv_switch_create(ui_ENVTab);
    lv_obj_set_width(ui_Switch6, 30);
    lv_obj_set_height(ui_Switch6, 17);
    lv_obj_set_x(ui_Switch6, -133);
    lv_obj_set_y(ui_Switch6, -71);
    lv_obj_set_align(ui_Switch6, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switch6, lv_color_hex(0x831918), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch6, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Switch6, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Switch6, lv_color_hex(0x690707), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch6, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_color(ui_Switch6, lv_color_hex(0xFF9400), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_main_stop(ui_Switch6, 100, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_stop(ui_Switch6, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_dir(ui_Switch6, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_blend_mode(ui_Switch6, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_Switch6, lv_color_hex(0x92EEFF), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_Switch6, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_object_set_themeable_style_property(ui_Switch6, LV_PART_INDICATOR | LV_STATE_CHECKED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_TEXTSHADOW);
    ui_object_set_themeable_style_property(ui_Switch6, LV_PART_INDICATOR | LV_STATE_CHECKED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_TEXTSHADOW);
    ui_object_set_themeable_style_property(ui_Switch6, LV_PART_INDICATOR | LV_STATE_CHECKED, LV_STYLE_BG_GRAD_COLOR,
                                           _ui_theme_color_TEXT);
    lv_obj_set_style_bg_main_stop(ui_Switch6, 10, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_stop(ui_Switch6, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_dir(ui_Switch6, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_object_set_themeable_style_property(ui_Switch6, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_TEXTSHADOW);
    ui_object_set_themeable_style_property(ui_Switch6, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_TEXTSHADOW);
    lv_obj_set_style_bg_color(ui_Switch6, lv_color_hex(0xEBC4B0), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch6, 220, LV_PART_KNOB | LV_STATE_CHECKED);

    ui_VCFTab = lv_tabview_add_tab(ui_TabView1, "VCF");

    ui_ChartVCFAttack = lv_chart_create(ui_VCFTab);
    lv_obj_set_width(ui_ChartVCFAttack, 77);
    lv_obj_set_height(ui_ChartVCFAttack, 64);
    lv_obj_set_x(ui_ChartVCFAttack, -215);
    lv_obj_set_y(ui_ChartVCFAttack, -53);
    lv_obj_set_align(ui_ChartVCFAttack, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_ChartVCFAttack, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_ChartVCFAttack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_ChartVCFAttack,
                    LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_ChartVCFAttack, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_ChartVCFAttack, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_ChartVCFAttack, 128);
    lv_chart_set_range(ui_ChartVCFAttack, LV_CHART_AXIS_PRIMARY_Y, 0, 4096);
    lv_chart_set_div_line_count(ui_ChartVCFAttack, 0, 0);
    lv_obj_set_style_radius(ui_ChartVCFAttack, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ChartVCFAttack, lv_color_hex(0x831918), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChartVCFAttack, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_ChartVCFAttack, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_GRAD_COLOR,
                                           _ui_theme_color_BACKGRCONTRAST);
    lv_obj_set_style_bg_main_stop(ui_ChartVCFAttack, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_ChartVCFAttack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_ChartVCFAttack, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_TEXTSHADOW);
    ui_object_set_themeable_style_property(ui_ChartVCFAttack, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_TEXTSHADOW);
    lv_obj_set_style_border_width(ui_ChartVCFAttack, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_ChartVCFAttack, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_LINE_COLOR,
                                           _ui_theme_color_TEXTCONTRAST);
    ui_object_set_themeable_style_property(ui_ChartVCFAttack, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_LINE_OPA,
                                           _ui_theme_alpha_TEXTCONTRAST);
    lv_obj_set_style_line_width(ui_ChartVCFAttack, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChartVCFAttack_Xaxis = lv_scale_create(ui_ChartVCFAttack);
    lv_scale_set_mode(ui_ChartVCFAttack_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_size(ui_ChartVCFAttack_Xaxis, lv_pct(100), 10);
    lv_obj_set_align(ui_ChartVCFAttack_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(ui_ChartVCFAttack_Xaxis, 10 + lv_obj_get_style_pad_bottom(ui_ChartVCFAttack,
                                                                           LV_PART_MAIN) + lv_obj_get_style_border_width(ui_ChartVCFAttack, LV_PART_MAIN));
    lv_obj_set_style_line_width(ui_ChartVCFAttack_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_ChartVCFAttack_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_ChartVCFAttack_Xaxis, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_ChartVCFAttack_Xaxis, 0, LV_PART_ITEMS);      //minor tick length
    lv_obj_set_style_length(ui_ChartVCFAttack_Xaxis, 0, LV_PART_INDICATOR);      //major tick length
    lv_scale_set_range(ui_ChartVCFAttack_Xaxis, 0, 0 > 0 ? 0 - 1 : 0);
    lv_scale_set_total_tick_count(ui_ChartVCFAttack_Xaxis, (0 > 0 ? 0 - 1 : 0) * 0 + 1);
    lv_scale_set_major_tick_every(ui_ChartVCFAttack_Xaxis, 0 >= 1 ? 0 : 1);
    ui_ChartVCFAttack_Yaxis1 = lv_scale_create(ui_ChartVCFAttack);
    lv_scale_set_mode(ui_ChartVCFAttack_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_align(ui_ChartVCFAttack_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_line_width(ui_ChartVCFAttack_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_ChartVCFAttack_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_ChartVCFAttack_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_ChartVCFAttack_Yaxis1, 0, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_ChartVCFAttack_Yaxis1, 0, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_range(ui_ChartVCFAttack_Yaxis1,  0, 4096);
    lv_scale_set_total_tick_count(ui_ChartVCFAttack_Yaxis1, (0 > 0 ? 0 - 1 : 0) * 0 + 1);
    lv_scale_set_major_tick_every(ui_ChartVCFAttack_Yaxis1, 0 >= 1 ? 0 : 1);
    lv_scale_set_label_show(ui_ChartVCFAttack_Yaxis1, false);
    ui_ChartVCFAttack_Yaxis2 = lv_scale_create(ui_ChartVCFAttack);
    lv_scale_set_mode(ui_ChartVCFAttack_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_size(ui_ChartVCFAttack_Yaxis2, 25, lv_pct(100));
    lv_obj_set_align(ui_ChartVCFAttack_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(ui_ChartVCFAttack_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_ChartVCFAttack,
                                                                           LV_PART_MAIN) + lv_obj_get_style_border_width(ui_ChartVCFAttack, LV_PART_MAIN) + 1);
    lv_obj_set_style_line_width(ui_ChartVCFAttack_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_ChartVCFAttack_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_ChartVCFAttack_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_ChartVCFAttack_Yaxis2, 0, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_ChartVCFAttack_Yaxis2, 0, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_ChartVCFAttack_Yaxis2, (0 > 0 ? 0 - 1 : 0) * 0 + 1);
    lv_scale_set_major_tick_every(ui_ChartVCFAttack_Yaxis2, 0 >= 1 ? 0 : 1);
    lv_scale_set_label_show(ui_ChartVCFAttack_Yaxis2, false);
    lv_chart_series_t * ui_ChartVCFAttack_series_1 = lv_chart_add_series(ui_ChartVCFAttack, lv_color_hex(0xB76052),
                                                                         LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_ChartVCFAttack_series_1_array[] = { 4095, 2040, 1702, 1593, 1504, 1428, 1363, 1305, 1254, 1207, 1164, 1125, 1088, 1054, 1023, 993, 965, 938, 913, 889, 866, 844, 823, 803, 784, 765, 748, 730, 714, 698, 682, 667, 652, 638, 624, 610, 597, 585, 572, 560, 548, 537, 525, 514, 503, 493, 482, 472, 462, 453, 443, 434, 424, 415, 407, 398, 389, 381, 373, 365, 357, 349, 341, 333, 326, 318, 311, 304, 297, 290, 283, 276, 269, 263, 256, 250, 244, 237, 231, 225, 219, 213, 207, 201, 195, 190, 184, 179, 173, 168, 162, 157, 152, 146, 141, 136, 131, 126, 121, 116, 112, 107, 102, 97, 93, 88, 83, 79, 74, 70, 65, 61, 57, 52, 48, 44, 40, 36, 32, 27, 23, 19, 15, 11, 8, 6, 4, 2, 0 };
    lv_chart_set_ext_y_array(ui_ChartVCFAttack, ui_ChartVCFAttack_series_1, ui_ChartVCFAttack_series_1_array);

    lv_obj_set_style_line_width(ui_ChartVCFAttack, 7, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_rounded(ui_ChartVCFAttack, true, LV_PART_ITEMS | LV_STATE_DEFAULT);


    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_pad(ui_ChartVCFAttack, LV_MAX3(10, 0, 25),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);   //workaround for ineffective 'overflow visible' flag
    lv_obj_set_style_outline_width(ui_ChartVCFAttack, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_ChartVCFDecay = lv_chart_create(ui_VCFTab);
    lv_obj_set_width(ui_ChartVCFDecay, 77);
    lv_obj_set_height(ui_ChartVCFDecay, 64);
    lv_obj_set_x(ui_ChartVCFDecay, -123);
    lv_obj_set_y(ui_ChartVCFDecay, -53);
    lv_obj_set_align(ui_ChartVCFDecay, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_ChartVCFDecay, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_ChartVCFDecay, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_ChartVCFDecay,
                    LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_ChartVCFDecay, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_ChartVCFDecay, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_ChartVCFDecay, 128);
    lv_chart_set_range(ui_ChartVCFDecay, LV_CHART_AXIS_PRIMARY_Y, 0, 4096);
    lv_chart_set_div_line_count(ui_ChartVCFDecay, 0, 0);
    lv_obj_set_style_radius(ui_ChartVCFDecay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ChartVCFDecay, lv_color_hex(0xF22D17), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChartVCFDecay, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_ChartVCFDecay, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_GRAD_COLOR,
                                           _ui_theme_color_BACKGRCONTRAST);
    lv_obj_set_style_bg_main_stop(ui_ChartVCFDecay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_ChartVCFDecay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ChartVCFDecay, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ChartVCFDecay, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ChartVCFDecay, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ChartVCFDecay, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ChartVCFDecay, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_ChartVCFDecay, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_LINE_COLOR,
                                           _ui_theme_color_TEXTCONTRAST);
    ui_object_set_themeable_style_property(ui_ChartVCFDecay, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_LINE_OPA,
                                           _ui_theme_alpha_TEXTCONTRAST);
    lv_obj_set_style_line_width(ui_ChartVCFDecay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChartVCFDecay_Xaxis = lv_scale_create(ui_ChartVCFDecay);
    lv_scale_set_mode(ui_ChartVCFDecay_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_size(ui_ChartVCFDecay_Xaxis, lv_pct(100), 10);
    lv_obj_set_align(ui_ChartVCFDecay_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(ui_ChartVCFDecay_Xaxis, 10 + lv_obj_get_style_pad_bottom(ui_ChartVCFDecay,
                                                                          LV_PART_MAIN) + lv_obj_get_style_border_width(ui_ChartVCFDecay, LV_PART_MAIN));
    lv_obj_set_style_line_width(ui_ChartVCFDecay_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_ChartVCFDecay_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_ChartVCFDecay_Xaxis, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_ChartVCFDecay_Xaxis, 0, LV_PART_ITEMS);      //minor tick length
    lv_obj_set_style_length(ui_ChartVCFDecay_Xaxis, 0, LV_PART_INDICATOR);      //major tick length
    lv_scale_set_range(ui_ChartVCFDecay_Xaxis, 0, 0 > 0 ? 0 - 1 : 0);
    lv_scale_set_total_tick_count(ui_ChartVCFDecay_Xaxis, (0 > 0 ? 0 - 1 : 0) * 0 + 1);
    lv_scale_set_major_tick_every(ui_ChartVCFDecay_Xaxis, 0 >= 1 ? 0 : 1);
    ui_ChartVCFDecay_Yaxis1 = lv_scale_create(ui_ChartVCFDecay);
    lv_scale_set_mode(ui_ChartVCFDecay_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_align(ui_ChartVCFDecay_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_line_width(ui_ChartVCFDecay_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_ChartVCFDecay_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_ChartVCFDecay_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_ChartVCFDecay_Yaxis1, 0, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_ChartVCFDecay_Yaxis1, 0, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_range(ui_ChartVCFDecay_Yaxis1,  0, 4096);
    lv_scale_set_total_tick_count(ui_ChartVCFDecay_Yaxis1, (0 > 0 ? 0 - 1 : 0) * 0 + 1);
    lv_scale_set_major_tick_every(ui_ChartVCFDecay_Yaxis1, 0 >= 1 ? 0 : 1);
    lv_scale_set_label_show(ui_ChartVCFDecay_Yaxis1, false);
    ui_ChartVCFDecay_Yaxis2 = lv_scale_create(ui_ChartVCFDecay);
    lv_scale_set_mode(ui_ChartVCFDecay_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_size(ui_ChartVCFDecay_Yaxis2, 25, lv_pct(100));
    lv_obj_set_align(ui_ChartVCFDecay_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(ui_ChartVCFDecay_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_ChartVCFDecay,
                                                                          LV_PART_MAIN) + lv_obj_get_style_border_width(ui_ChartVCFDecay, LV_PART_MAIN) + 1);
    lv_obj_set_style_line_width(ui_ChartVCFDecay_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_ChartVCFDecay_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_ChartVCFDecay_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_ChartVCFDecay_Yaxis2, 0, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_ChartVCFDecay_Yaxis2, 0, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_ChartVCFDecay_Yaxis2, (0 > 0 ? 0 - 1 : 0) * 0 + 1);
    lv_scale_set_major_tick_every(ui_ChartVCFDecay_Yaxis2, 0 >= 1 ? 0 : 1);
    lv_scale_set_label_show(ui_ChartVCFDecay_Yaxis2, false);
    lv_chart_series_t * ui_ChartVCFDecay_series_1 = lv_chart_add_series(ui_ChartVCFDecay, lv_color_hex(0xB76052),
                                                                        LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_ChartVCFDecay_series_1_array[] = { 4095, 2040, 1702, 1593, 1504, 1428, 1363, 1305, 1254, 1207, 1164, 1125, 1088, 1054, 1023, 993, 965, 938, 913, 889, 866, 844, 823, 803, 784, 765, 748, 730, 714, 698, 682, 667, 652, 638, 624, 610, 597, 585, 572, 560, 548, 537, 525, 514, 503, 493, 482, 472, 462, 453, 443, 434, 424, 415, 407, 398, 389, 381, 373, 365, 357, 349, 341, 333, 326, 318, 311, 304, 297, 290, 283, 276, 269, 263, 256, 250, 244, 237, 231, 225, 219, 213, 207, 201, 195, 190, 184, 179, 173, 168, 162, 157, 152, 146, 141, 136, 131, 126, 121, 116, 112, 107, 102, 97, 93, 88, 83, 79, 74, 70, 65, 61, 57, 52, 48, 44, 40, 36, 32, 27, 23, 19, 15, 11, 8, 6, 4, 2, 0 };
    lv_chart_set_ext_y_array(ui_ChartVCFDecay, ui_ChartVCFDecay_series_1, ui_ChartVCFDecay_series_1_array);

    lv_obj_set_style_line_width(ui_ChartVCFDecay, 7, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_rounded(ui_ChartVCFDecay, true, LV_PART_ITEMS | LV_STATE_DEFAULT);


    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_pad(ui_ChartVCFDecay, LV_MAX3(10, 0, 25),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);   //workaround for ineffective 'overflow visible' flag
    lv_obj_set_style_outline_width(ui_ChartVCFDecay, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_Switch1 = lv_switch_create(ui_VCFTab);
    lv_obj_set_width(ui_Switch1, 30);
    lv_obj_set_height(ui_Switch1, 15);
    lv_obj_set_x(ui_Switch1, -129);
    lv_obj_set_y(ui_Switch1, 7);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);


    ui_VCATab = lv_tabview_add_tab(ui_TabView1, "VCA");

    ui_SettingsTab = lv_tabview_add_tab(ui_TabView1, "OPTS");

    ui_ENVTab1 = lv_tabview_add_tab(ui_TabView1, "ENV");

    ui_Label5 = lv_label_create(ui_ENVTab1);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -45);
    lv_obj_set_y(ui_Label5, -71);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, " VCF restart attack");
    ui_object_set_themeable_style_property(ui_Label5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TEXTSHADOW);
    ui_object_set_themeable_style_property(ui_Label5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TEXTSHADOW);
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Label5);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -1);
    lv_obj_set_y(ui_Label6, 1);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, " VCF restart attack");
    ui_object_set_themeable_style_property(ui_Label6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TEXT);
    ui_object_set_themeable_style_property(ui_Label6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TEXT);
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_ENVTab1);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -46);
    lv_obj_set_y(ui_Label7, -91);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, " VCA restart attack");
    ui_object_set_themeable_style_property(ui_Label7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TEXTSHADOW);
    ui_object_set_themeable_style_property(ui_Label7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TEXTSHADOW);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Label7);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -1);
    lv_obj_set_y(ui_Label8, 1);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, " VCA restart attack");
    ui_object_set_themeable_style_property(ui_Label8, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TEXT);
    ui_object_set_themeable_style_property(ui_Label8, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TEXT);
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

}
