// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: DCO_v4

#include "ui.h"

void ui_Main_screen_init(void)
{
    ui_Main = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Main, lv_color_hex(0x566876), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Main, lv_color_hex(0xE1913B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Main, 240, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Main, &ui_font_radj22SEMI, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetNumberContainer = lv_obj_create(ui_Main);
    lv_obj_remove_style_all(ui_PresetNumberContainer);
    lv_obj_set_width(ui_PresetNumberContainer, 320);
    lv_obj_set_height(ui_PresetNumberContainer, 130);
    lv_obj_set_x(ui_PresetNumberContainer, 0);
    lv_obj_set_y(ui_PresetNumberContainer, 21);
    lv_obj_set_align(ui_PresetNumberContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PresetNumberContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_PresetNumberContainer, lv_color_hex(0xBD814A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PresetNumberContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PresetNumberContainer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetNShadow = lv_label_create(ui_PresetNumberContainer);
    lv_obj_set_width(ui_PresetNShadow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PresetNShadow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PresetNShadow, -3);
    lv_obj_set_y(ui_PresetNShadow, -4);
    lv_obj_set_align(ui_PresetNShadow, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PresetNShadow, "208");
    lv_obj_set_style_text_color(ui_PresetNShadow, lv_color_hex(0xFF3B18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetNShadow, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_PresetNShadow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_PresetNShadow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PresetNShadow, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetNShadow, &ui_font_radj148Semi, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PresetNShadow, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetN = lv_label_create(ui_PresetNShadow);
    lv_obj_set_width(ui_PresetN, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PresetN, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PresetN, -13);
    lv_obj_set_y(ui_PresetN, 9);
    lv_obj_set_align(ui_PresetN, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PresetN, "208");
    lv_obj_set_style_text_color(ui_PresetN, lv_color_hex(0xE1913B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetN, 240, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_PresetN, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_PresetN, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PresetN, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetN, &ui_font_radjSemiBold140, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PresetN, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TopBarPanel = lv_obj_create(ui_Main);
    lv_obj_set_width(ui_TopBarPanel, 320);
    lv_obj_set_height(ui_TopBarPanel, 49);
    lv_obj_set_align(ui_TopBarPanel, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_TopBarPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TopBarPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TopBarPanel, lv_color_hex(0x181008), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TopBarPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TopBarPanel, lv_color_hex(0xB47D41), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TopBarPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TopBarPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OSC1Level = ui_BAR2_create(ui_TopBarPanel);
    lv_obj_set_x(ui_OSC1Level, 0);
    lv_obj_set_y(ui_OSC1Level, -15);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    ui_OSC2Level = ui_BAR2_create(ui_TopBarPanel);
    lv_obj_set_x(ui_OSC2Level, 0);
    lv_obj_set_y(ui_OSC2Level, 0);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    ui_SUBLevel = ui_BAR2_create(ui_TopBarPanel);
    lv_obj_set_x(ui_SUBLevel, 0);
    lv_obj_set_y(ui_SUBLevel, 15);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    ui_PresetNamePanel = lv_obj_create(ui_Main);
    lv_obj_set_width(ui_PresetNamePanel, 320);
    lv_obj_set_height(ui_PresetNamePanel, 29);
    lv_obj_set_x(ui_PresetNamePanel, 0);
    lv_obj_set_y(ui_PresetNamePanel, -58);
    lv_obj_set_align(ui_PresetNamePanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PresetNamePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PresetNamePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PresetNamePanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PresetNamePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PresetNamePanel, lv_color_hex(0xAC7939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PresetNamePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PresetNamePanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BottomContainer = lv_obj_create(ui_Main);
    lv_obj_remove_style_all(ui_BottomContainer);
    lv_obj_set_width(ui_BottomContainer, 320);
    lv_obj_set_height(ui_BottomContainer, 35);
    lv_obj_set_x(ui_BottomContainer, 0);
    lv_obj_set_y(ui_BottomContainer, 102);
    lv_obj_set_align(ui_BottomContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_BottomContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_BottomContainer, lv_color_hex(0xB47D41), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BottomContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BottomContainer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_BottomContainer, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetNameShadow = lv_label_create(ui_BottomContainer);
    lv_obj_set_width(ui_PresetNameShadow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PresetNameShadow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PresetNameShadow, 9);
    lv_obj_set_y(ui_PresetNameShadow, 8);
    lv_label_set_text(ui_PresetNameShadow, "PRESET NAME");
    lv_obj_set_style_text_color(ui_PresetNameShadow, lv_color_hex(0xEA6E00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetNameShadow, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetNameShadow, &ui_font_radj26, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PresetNameShadow, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetName = lv_label_create(ui_BottomContainer);
    lv_obj_set_width(ui_PresetName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PresetName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PresetName, 11);
    lv_obj_set_y(ui_PresetName, 5);
    lv_label_set_text(ui_PresetName, "PRESET NAME");
    lv_obj_set_style_text_color(ui_PresetName, lv_color_hex(0xC48A30), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetName, &ui_font_radj26Medium, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PresetName, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BottomMessagePanel = lv_obj_create(ui_BottomContainer);
    lv_obj_set_width(ui_BottomMessagePanel, 313);
    lv_obj_set_height(ui_BottomMessagePanel, 29);
    lv_obj_set_x(ui_BottomMessagePanel, -1);
    lv_obj_set_y(ui_BottomMessagePanel, 0);
    lv_obj_set_align(ui_BottomMessagePanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BottomMessagePanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_BottomMessagePanel,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_BottomMessagePanel, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_BottomMessagePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BottomMessagePanel, lv_color_hex(0x415562), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BottomMessagePanel, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_BottomMessagePanel, lv_color_hex(0x435255), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_BottomMessagePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_BottomMessagePanel, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_BottomMessagePanel, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BottomMessagePanel, lv_color_hex(0xFF5700), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BottomMessagePanel, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BottomMessagePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_BottomMessagePanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_BottomMessagePanel, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_BottomMessagePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CommandMessageShadow = lv_label_create(ui_BottomMessagePanel);
    lv_obj_set_width(ui_CommandMessageShadow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CommandMessageShadow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CommandMessageShadow, -7);
    lv_obj_set_y(ui_CommandMessageShadow, -9);
    lv_label_set_text(ui_CommandMessageShadow, "COMMAND MESSAGES");
    lv_obj_set_style_text_color(ui_CommandMessageShadow, lv_color_hex(0xFF3B18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CommandMessageShadow, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_CommandMessageShadow, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CommandMessageShadow, &ui_font_radj26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CommandMessage = lv_label_create(ui_BottomMessagePanel);
    lv_obj_set_width(ui_CommandMessage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CommandMessage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CommandMessage, -5);
    lv_obj_set_y(ui_CommandMessage, -11);
    lv_label_set_text(ui_CommandMessage, "COMMAND MESSAGES");
    lv_obj_set_style_text_color(ui_CommandMessage, lv_color_hex(0xE1913B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CommandMessage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_CommandMessage, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CommandMessage, &ui_font_radj26Medium, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_CommandMessage, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CommandValueShadow = lv_label_create(ui_BottomMessagePanel);
    lv_obj_set_width(ui_CommandValueShadow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CommandValueShadow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CommandValueShadow, 255);
    lv_obj_set_y(ui_CommandValueShadow, -9);
    lv_label_set_text(ui_CommandValueShadow, "127");
    lv_obj_set_style_text_color(ui_CommandValueShadow, lv_color_hex(0xFF3B18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CommandValueShadow, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_CommandValueShadow, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CommandValueShadow, &ui_font_radj26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CommandValue = lv_label_create(ui_BottomMessagePanel);
    lv_obj_set_width(ui_CommandValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CommandValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CommandValue, 253);
    lv_obj_set_y(ui_CommandValue, -11);
    lv_label_set_text(ui_CommandValue, "127");
    lv_obj_set_style_text_color(ui_CommandValue, lv_color_hex(0xE1913B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CommandValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_CommandValue, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CommandValue, &ui_font_radj26Medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetSavePanel = lv_obj_create(ui_Main);
    lv_obj_set_width(ui_PresetSavePanel, 296);
    lv_obj_set_height(ui_PresetSavePanel, 216);
    lv_obj_set_x(ui_PresetSavePanel, 0);
    lv_obj_set_y(ui_PresetSavePanel, -1);
    lv_obj_set_align(ui_PresetSavePanel, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_PresetSavePanel, LV_STATE_USER_1);       /// States
    lv_obj_add_flag(ui_PresetSavePanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_PresetSavePanel,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_PresetSavePanel, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_PresetSavePanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PresetSavePanel, lv_color_hex(0x831918), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PresetSavePanel, 220, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PresetSavePanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PresetSavePanel, lv_color_hex(0x810202), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_PresetSavePanel, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_PresetSavePanel, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_PresetSavePanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PresetSavePanel, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetSaveFromTitleShadow = lv_label_create(ui_PresetSavePanel);
    lv_obj_set_width(ui_PresetSaveFromTitleShadow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PresetSaveFromTitleShadow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PresetSaveFromTitleShadow, -6);
    lv_obj_set_y(ui_PresetSaveFromTitleShadow, -10);
    lv_label_set_text(ui_PresetSaveFromTitleShadow, "Saving FROM:");
    lv_obj_set_style_text_color(ui_PresetSaveFromTitleShadow, lv_color_hex(0xE55E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetSaveFromTitleShadow, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetSaveFromTitleShadow, &ui_font_Square22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PresetSaveFromTitleShadow, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetSaveFromTitle = lv_label_create(ui_PresetSavePanel);
    lv_obj_set_width(ui_PresetSaveFromTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PresetSaveFromTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PresetSaveFromTitle, -4);
    lv_obj_set_y(ui_PresetSaveFromTitle, -7);
    lv_label_set_text(ui_PresetSaveFromTitle, "Saving FROM:");
    lv_obj_set_style_text_color(ui_PresetSaveFromTitle, lv_color_hex(0xE55E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetSaveFromTitle, 240, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetSaveFromTitle, &ui_font_Square22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PresetSaveFromTitle, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetNOLDShadow = lv_label_create(ui_PresetSavePanel);
    lv_obj_set_width(ui_PresetNOLDShadow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PresetNOLDShadow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PresetNOLDShadow, 70);
    lv_obj_set_y(ui_PresetNOLDShadow, -85);
    lv_obj_set_align(ui_PresetNOLDShadow, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PresetNOLDShadow, "208");
    lv_obj_set_style_text_color(ui_PresetNOLDShadow, lv_color_hex(0xE55E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetNOLDShadow, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_PresetNOLDShadow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_PresetNOLDShadow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PresetNOLDShadow, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetNOLDShadow, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PresetNOLDShadow, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetNOLD = lv_label_create(ui_PresetSavePanel);
    lv_obj_set_width(ui_PresetNOLD, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PresetNOLD, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PresetNOLD, 74);
    lv_obj_set_y(ui_PresetNOLD, -84);
    lv_obj_set_align(ui_PresetNOLD, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PresetNOLD, "208");
    lv_obj_set_style_text_color(ui_PresetNOLD, lv_color_hex(0xE55E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetNOLD, 230, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_PresetNOLD, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_PresetNOLD, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PresetNOLD, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetNOLD, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PresetNOLD, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetNameOLDShadow = lv_label_create(ui_PresetSavePanel);
    lv_obj_set_width(ui_PresetNameOLDShadow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PresetNameOLDShadow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PresetNameOLDShadow, 37);
    lv_obj_set_y(ui_PresetNameOLDShadow, 35);
    lv_label_set_text(ui_PresetNameOLDShadow, "PRESET NAME");
    lv_obj_set_style_text_color(ui_PresetNameOLDShadow, lv_color_hex(0xE55E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetNameOLDShadow, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetNameOLDShadow, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PresetNameOLDShadow, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetNameOLD = lv_label_create(ui_PresetSavePanel);
    lv_obj_set_width(ui_PresetNameOLD, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PresetNameOLD, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PresetNameOLD, 40);
    lv_obj_set_y(ui_PresetNameOLD, 37);
    lv_label_set_text(ui_PresetNameOLD, "PRESET NAME");
    lv_obj_set_style_text_color(ui_PresetNameOLD, lv_color_hex(0xE55E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetNameOLD, 240, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetNameOLD, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PresetNameOLD, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetSaveToShadow = lv_label_create(ui_PresetSavePanel);
    lv_obj_set_width(ui_PresetSaveToShadow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PresetSaveToShadow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PresetSaveToShadow, -10);
    lv_obj_set_y(ui_PresetSaveToShadow, 76);
    lv_label_set_text(ui_PresetSaveToShadow, "TO:");
    lv_obj_set_style_text_color(ui_PresetSaveToShadow, lv_color_hex(0xE55E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetSaveToShadow, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetSaveToShadow, &ui_font_Square22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PresetSaveToShadow, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetSaveTo = lv_label_create(ui_PresetSavePanel);
    lv_obj_set_width(ui_PresetSaveTo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PresetSaveTo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PresetSaveTo, -6);
    lv_obj_set_y(ui_PresetSaveTo, 79);
    lv_label_set_text(ui_PresetSaveTo, "TO:");
    lv_obj_set_style_text_color(ui_PresetSaveTo, lv_color_hex(0xE55E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetSaveTo, 240, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetSaveTo, &ui_font_Square22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PresetSaveTo, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetNNewShadow = lv_label_create(ui_PresetSavePanel);
    lv_obj_set_width(ui_PresetNNewShadow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PresetNNewShadow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PresetNNewShadow, 68);
    lv_obj_set_y(ui_PresetNNewShadow, 17);
    lv_obj_set_align(ui_PresetNNewShadow, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PresetNNewShadow, "208");
    lv_obj_set_style_text_color(ui_PresetNNewShadow, lv_color_hex(0xE55E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetNNewShadow, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_PresetNNewShadow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_PresetNNewShadow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PresetNNewShadow, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetNNewShadow, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PresetNNewShadow, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetNNew = lv_label_create(ui_PresetSavePanel);
    lv_obj_set_width(ui_PresetNNew, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PresetNNew, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PresetNNew, 72);
    lv_obj_set_y(ui_PresetNNew, 18);
    lv_obj_set_align(ui_PresetNNew, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PresetNNew, "208");
    lv_obj_set_style_text_color(ui_PresetNNew, lv_color_hex(0xE55E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetNNew, 230, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_PresetNNew, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_PresetNNew, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PresetNNew, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetNNew, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PresetNNew, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetNameNew = lv_label_create(ui_PresetSavePanel);
    lv_obj_set_width(ui_PresetNameNew, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PresetNameNew, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PresetNameNew, 40);
    lv_obj_set_y(ui_PresetNameNew, 145);
    lv_label_set_text(ui_PresetNameNew, "PRESET NAME");
    lv_obj_set_style_text_color(ui_PresetNameNew, lv_color_hex(0xE55E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetNameNew, 240, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetNameNew, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PresetNameNew, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetNameNewShadow = lv_label_create(ui_PresetSavePanel);
    lv_obj_set_width(ui_PresetNameNewShadow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PresetNameNewShadow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PresetNameNewShadow, 37);
    lv_obj_set_y(ui_PresetNameNewShadow, 142);
    lv_label_set_text(ui_PresetNameNewShadow, "PRESET NAME");
    lv_obj_set_style_text_color(ui_PresetNameNewShadow, lv_color_hex(0xE55E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetNameNewShadow, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetNameNewShadow, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PresetNameNewShadow, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetNewName = lv_textarea_create(ui_Main);
    lv_obj_set_width(ui_PresetNewName, 255);
    lv_obj_set_height(ui_PresetNewName, LV_SIZE_CONTENT);    /// 51
    lv_obj_set_x(ui_PresetNewName, 4);
    lv_obj_set_y(ui_PresetNewName, 54);
    lv_obj_set_align(ui_PresetNewName, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_PresetNewName, 12);
    lv_textarea_set_one_line(ui_PresetNewName, true);
    lv_obj_add_state(ui_PresetNewName, LV_STATE_FOCUSED);       /// States
    lv_obj_add_flag(ui_PresetNewName, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_WITH_ARROW);     /// Flags
    lv_obj_remove_flag(ui_PresetNewName,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_PresetNewName, lv_color_hex(0x8C0E0E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetNewName, 240, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PresetNewName, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetNewName, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PresetNewName, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PresetNewName, lv_color_hex(0xF51419), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PresetNewName, 210, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_PresetNewName, lv_color_hex(0xFFAF2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PresetNewName, lv_color_hex(0x050000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PresetNewName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PresetNewName, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PresetNewName, lv_color_hex(0xFF0C00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_PresetNewName, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_PresetNewName, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_PresetNewName, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_PresetNewName, lv_color_hex(0x1D0101), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetNewName, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PresetNewName, lv_color_hex(0xE50B00), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PresetNewName, 160, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PresetNewName, LV_BLEND_MODE_ADDITIVE, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_PresetNewName, lv_color_hex(0xFF1A15), LV_PART_CURSOR | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_PresetNewName, 220, LV_PART_CURSOR | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_PresetNewName, lv_color_hex(0x7C1515), LV_PART_CURSOR | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_PresetNewName, 255, LV_PART_CURSOR | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_PresetNewName, lv_color_hex(0xFF0000), LV_PART_CURSOR | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_PresetNewName, 150, LV_PART_CURSOR | LV_STATE_FOCUSED);

    ui_PresetSavedMesage = lv_textarea_create(ui_Main);
    lv_obj_set_width(ui_PresetSavedMesage, 253);
    lv_obj_set_height(ui_PresetSavedMesage, 51);
    lv_obj_set_x(ui_PresetSavedMesage, 3);
    lv_obj_set_y(ui_PresetSavedMesage, 12);
    lv_obj_set_align(ui_PresetSavedMesage, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_PresetSavedMesage, "PRESET SAVED");
    lv_obj_add_flag(ui_PresetSavedMesage, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_PresetSavedMesage, lv_color_hex(0xFFB131), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetSavedMesage, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PresetSavedMesage, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetSavedMesage, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PresetSavedMesage, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PresetSavedMesage, lv_color_hex(0xF51419), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PresetSavedMesage, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_PresetSavedMesage, LV_GRAD_DIR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PresetSavedMesage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PresetSavedMesage, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PresetSavedMesage, lv_color_hex(0xFF0C00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_PresetSavedMesage, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_PresetSavedMesage, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_PresetSavedMesage, 30, LV_PART_MAIN | LV_STATE_DEFAULT);



}
