// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: DCO_v4_ILI9488

#include "ui.h"

const ui_theme_variable_t _ui_theme_color_TEXT[2] = {0xE1913B, 0xE1913B};
const ui_theme_variable_t _ui_theme_alpha_TEXT[2] = {240, 240};

const ui_theme_variable_t _ui_theme_color_TEXTSHADOW[2] = {0xFF3B18, 0xFF3B18};
const ui_theme_variable_t _ui_theme_alpha_TEXTSHADOW[2] = {150, 150};

const ui_theme_variable_t _ui_theme_color_BACKGROUND[2] = {0x566876, 0x566876};
const ui_theme_variable_t _ui_theme_alpha_BACKGROUND[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_BACKGRCONTRAST[2] = {0x831918, 0x831918};
const ui_theme_variable_t _ui_theme_alpha_BACKGRCONTRAST[2] = {220, 220};

const ui_theme_variable_t _ui_theme_color_TEXTCONTRAST[2] = {0xE55E2E, 0xE55E2E};
const ui_theme_variable_t _ui_theme_alpha_TEXTCONTRAST[2] = {220, 220};
uint8_t ui_theme_idx = UI_THEME_FELA;

void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

