// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: DCO_v4_ILI9488

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_TEXT 0
#define UI_THEME_COLOR_TEXTSHADOW 1
#define UI_THEME_COLOR_BACKGROUND 2
#define UI_THEME_COLOR_BACKGRCONTRAST 3
#define UI_THEME_COLOR_TEXTCONTRAST 4

#define UI_THEME_DEFAULT 0

#define UI_THEME_FELA 1

extern const ui_theme_variable_t _ui_theme_color_TEXT[2];
extern const ui_theme_variable_t _ui_theme_alpha_TEXT[2];

extern const ui_theme_variable_t _ui_theme_color_TEXTSHADOW[2];
extern const ui_theme_variable_t _ui_theme_alpha_TEXTSHADOW[2];

extern const ui_theme_variable_t _ui_theme_color_BACKGROUND[2];
extern const ui_theme_variable_t _ui_theme_alpha_BACKGROUND[2];

extern const ui_theme_variable_t _ui_theme_color_BACKGRCONTRAST[2];
extern const ui_theme_variable_t _ui_theme_alpha_BACKGRCONTRAST[2];

extern const ui_theme_variable_t _ui_theme_color_TEXTCONTRAST[2];
extern const ui_theme_variable_t _ui_theme_alpha_TEXTCONTRAST[2];

extern const uint32_t * ui_theme_colors[2];
extern const uint8_t * ui_theme_alphas[2];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
